-- english_grammar question_bank seed — generated from c:/git_repository/5minuate_study/supabase/seed/english_grammar_day01-05.json
-- Supabase SQL 에디터에서 실행하세요 (question_bank 테이블이 먼저 생성되어 있어야 함)

insert into question_bank (curriculum_id, day_num, difficulty, question, type, options, answer, explanation) values
  ('english_grammar', 1, 'beginner', '"The dog runs fast." 이 문장에서 주어(S)는?', 'multiple_choice', '["The dog","runs","fast","없음"]'::jsonb, 'The dog', '문장의 동작을 하는 주체인 The dog이 주어입니다.'),
  ('english_grammar', 1, 'beginner', '"The bird sings." 이 문장은 몇 형식인가?', 'multiple_choice', '["1형식","2형식","3형식","4형식"]'::jsonb, '1형식', '주어+동사(S+V)만으로 완전한 문장이므로 1형식입니다.'),
  ('english_grammar', 1, 'beginner', '"She looks happy."에서 happy의 역할은?', 'multiple_choice', '["목적어","보어","부사","동사"]'::jsonb, '보어', 'looks 같은 연결동사 뒤에서 주어를 보충 설명하는 주격보어입니다.'),
  ('english_grammar', 1, 'beginner', '"I love music." 이 문장은 몇 형식인가?', 'multiple_choice', '["1형식","2형식","3형식","4형식"]'::jsonb, '3형식', '주어+타동사+목적어(S+V+O) 구조이므로 3형식입니다.'),
  ('english_grammar', 1, 'beginner', '다음 중 4형식 문장은?', 'multiple_choice', '["He gave me a gift.","I love music.","She looks happy.","The bird sings."]'::jsonb, 'He gave me a gift.', '수여동사 gave가 간접목적어(me)와 직접목적어(a gift)를 모두 취하는 4형식입니다.'),
  ('english_grammar', 1, 'beginner', '"They call him a genius."에서 a genius의 역할은?', 'multiple_choice', '["목적어","목적격보어","주어","부사"]'::jsonb, '목적격보어', '목적어 him을 보충 설명하는 목적격보어입니다.'),
  ('english_grammar', 1, 'beginner', '"I love music."에서 목적어를 쓰시오.', 'short_answer', null, 'music', '타동사 love의 대상이 되는 목적어는 music입니다.'),
  ('english_grammar', 1, 'beginner', '''주어+동사+목적어+목적격보어''로 이루어진 문장 형식은 몇 형식인가?', 'short_answer', null, '5형식', 'S+V+O+OC 구조는 5형식입니다.'),
  ('english_grammar', 1, 'intermediate', '다음 중 2형식 문장으로 옳은 것은?', 'multiple_choice', '["She looks happy.","He gave me a gift.","They call him a genius.","I love music."]'::jsonb, 'She looks happy.', 'S+V+C 구조로 주격보어 happy가 주어를 설명하는 2형식입니다.'),
  ('english_grammar', 1, 'intermediate', '"He gave me a gift."에서 me의 문법적 역할은?', 'multiple_choice', '["직접목적어","간접목적어","보어","주어"]'::jsonb, '간접목적어', '''~에게''에 해당하는 me는 간접목적어, a gift가 직접목적어입니다.'),
  ('english_grammar', 1, 'intermediate', '다음 중 문장 형식이 다른 하나는?', 'multiple_choice', '["I love music.","She studies math.","The bird sings.","He plays soccer."]'::jsonb, 'The bird sings.', '나머지는 모두 S+V+O(3형식)이지만 The bird sings는 목적어가 없는 1형식입니다.'),
  ('english_grammar', 1, 'intermediate', '"They call him a genius."와 같은 문형인 것은?', 'multiple_choice', '["They made her happy.","She looks happy.","I love music.","He gave me a gift."]'::jsonb, 'They made her happy.', '목적어(her)+목적격보어(happy) 구조의 5형식으로 동일한 문형입니다.'),
  ('english_grammar', 1, 'intermediate', '다음 중 수여동사(4형식 동사)가 아닌 것은?', 'multiple_choice', '["give","send","love","teach"]'::jsonb, 'love', 'give, send, teach는 간접·직접목적어를 취하는 수여동사이지만 love는 3형식 타동사입니다.'),
  ('english_grammar', 1, 'intermediate', '2형식 문장의 주격보어로 쓰이기 어려운 것은?', 'multiple_choice', '["형용사","명사","부사","to부정사"]'::jsonb, '부사', '주격보어는 주어를 설명하는 형용사나 명사가 오며, 부사는 보어로 쓰이지 않습니다.'),
  ('english_grammar', 1, 'intermediate', '"He gave me a gift."의 문장 형식을 숫자로 쓰시오.', 'short_answer', null, '4형식', '간접목적어+직접목적어 구조이므로 4형식입니다.'),
  ('english_grammar', 1, 'intermediate', '"They call him a genius."에서 목적격보어를 쓰시오.', 'short_answer', null, 'a genius', '목적어 him을 설명하는 목적격보어는 a genius입니다.'),
  ('english_grammar', 1, 'advanced', '다음 중 5형식 문장인 것은?', 'multiple_choice', '["He made her happy.","He made a cake.","She looks happy.","I love music."]'::jsonb, 'He made her happy.', '목적어 her + 목적격보어 happy 구조로 5형식입니다.'),
  ('english_grammar', 1, 'advanced', '"I found the book interesting."의 문장 형식은?', 'multiple_choice', '["3형식","4형식","5형식","2형식"]'::jsonb, '5형식', '목적어 the book을 목적격보어 interesting이 설명하는 5형식입니다.'),
  ('english_grammar', 1, 'advanced', '간접목적어와 직접목적어, 즉 목적어가 2개 오는 문형은?', 'multiple_choice', '["1형식","2형식","4형식","5형식"]'::jsonb, '4형식', '4형식(S+V+IO+DO)은 목적어를 두 개 취합니다.'),
  ('english_grammar', 1, 'advanced', '"He made her a cake."를 3형식으로 바르게 바꾼 것은?', 'multiple_choice', '["He made a cake for her.","He made a cake to her.","He made her for a cake.","He made cake her."]'::jsonb, 'He made a cake for her.', 'make, buy, cook 등은 4형식→3형식 전환 시 전치사 for를 씁니다.'),
  ('english_grammar', 1, 'advanced', '다음 중 목적어가 아닌 보어를 필요로 하는 동사는?', 'multiple_choice', '["love","seem","eat","read"]'::jsonb, 'seem', 'seem은 연결동사로 주격보어를 취하는 2형식 동사입니다.'),
  ('english_grammar', 1, 'advanced', '"She found him a good teacher."에서 a good teacher의 역할로 옳은 것은?', 'multiple_choice', '["him에 대한 목적격보어","직접목적어","부사","주어"]'::jsonb, 'him에 대한 목적격보어', 'found가 5형식으로 쓰여 him을 a good teacher로 평가한다는 뜻입니다.'),
  ('english_grammar', 1, 'advanced', '"He made her a cake."를 전치사 for를 사용한 3형식 문장으로 바꿔 쓰시오.', 'short_answer', null, 'He made a cake for her.', '4형식의 간접목적어는 for+목적어 형태로 뒤에 옮길 수 있습니다.'),
  ('english_grammar', 1, 'advanced', '"I found the book interesting."에서 목적격보어를 쓰시오.', 'short_answer', null, 'interesting', '목적어 the book의 상태를 설명하는 목적격보어입니다.'),
  ('english_grammar', 2, 'beginner', '''book''은 어떤 품사인가?', 'multiple_choice', '["명사","동사","형용사","부사"]'::jsonb, '명사', 'book은 사물의 이름을 나타내는 명사입니다.'),
  ('english_grammar', 2, 'beginner', '''quickly''는 어떤 품사인가?', 'multiple_choice', '["형용사","부사","명사","전치사"]'::jsonb, '부사', '-ly로 끝나며 동사를 수식하는 부사입니다.'),
  ('english_grammar', 2, 'beginner', '''and''는 어떤 품사인가?', 'multiple_choice', '["접속사","전치사","부사","감탄사"]'::jsonb, '접속사', '단어나 절을 연결하는 접속사입니다.'),
  ('english_grammar', 2, 'beginner', '''beautiful''은 어떤 품사인가?', 'multiple_choice', '["형용사","부사","동사","명사"]'::jsonb, '형용사', '명사를 수식하는 형용사입니다.'),
  ('english_grammar', 2, 'beginner', '''in''은 어떤 품사인가?', 'multiple_choice', '["전치사","접속사","부사","명사"]'::jsonb, '전치사', '명사 앞에 놓여 위치·관계를 나타내는 전치사입니다.'),
  ('english_grammar', 2, 'beginner', '감정을 표현하는 품사는?', 'multiple_choice', '["감탄사","접속사","전치사","부사"]'::jsonb, '감탄사', 'Oh!, Wow!처럼 감정을 나타내는 품사가 감탄사입니다.'),
  ('english_grammar', 2, 'beginner', '''run''의 품사를 쓰시오.', 'short_answer', null, '동사', '동작을 나타내는 run은 동사입니다.'),
  ('english_grammar', 2, 'beginner', '''they''의 품사를 쓰시오.', 'short_answer', null, '대명사', '명사를 대신하는 they는 대명사입니다.'),
  ('english_grammar', 2, 'intermediate', '다음 중 부사가 아닌 것은?', 'multiple_choice', '["quickly","here","always","happy"]'::jsonb, 'happy', 'happy는 형용사이며 나머지는 부사입니다.'),
  ('english_grammar', 2, 'intermediate', '"The book is on the table."에서 전치사는?', 'multiple_choice', '["on","is","book","table"]'::jsonb, 'on', 'on은 table 앞에서 위치를 나타내는 전치사입니다.'),
  ('english_grammar', 2, 'intermediate', '명사를 대신하는 품사는?', 'multiple_choice', '["대명사","형용사","부사","접속사"]'::jsonb, '대명사', 'I, he, they처럼 명사를 대신하는 품사가 대명사입니다.'),
  ('english_grammar', 2, 'intermediate', '다음 중 모두 접속사로만 짝지어진 것은?', 'multiple_choice', '["and, but, because","in, on, at","quickly, here","book, table"]'::jsonb, 'and, but, because', 'and, but, because는 단어나 절을 연결하는 접속사입니다.'),
  ('english_grammar', 2, 'intermediate', '"I''ll back you up."에서 back의 품사는?', 'multiple_choice', '["동사","명사","부사","형용사"]'::jsonb, '동사', '''지원하다''라는 뜻의 동사로 쓰였습니다.'),
  ('english_grammar', 2, 'intermediate', '형용사가 명사를 수식하는 예로 옳은 것은?', 'multiple_choice', '["a large house","run quickly","in the box","and then"]'::jsonb, 'a large house', 'large가 명사 house를 수식하는 형용사입니다.'),
  ('english_grammar', 2, 'intermediate', '"She studies math."에서 studies의 품사를 쓰시오.', 'short_answer', null, '동사', '동작을 나타내는 studies는 동사입니다.'),
  ('english_grammar', 2, 'intermediate', '"Oh! That''s amazing."에서 Oh의 품사를 쓰시오.', 'short_answer', null, '감탄사', '감정을 표현하는 Oh는 감탄사입니다.'),
  ('english_grammar', 2, 'advanced', '다음 중 같은 단어의 품사 전환 예로 옳지 않은 것은?', 'multiple_choice', '["and(그리고,접속사) / and(등,명사)","back(뒤로,부사) / back(등,명사)","book(책,명사) / book(예약하다,동사)","light(빛,명사) / light(가벼운,형용사)"]'::jsonb, 'and(그리고,접속사) / and(등,명사)', 'and는 접속사로만 쓰이며 명사로 전환되지 않습니다.'),
  ('english_grammar', 2, 'advanced', '"I saw her fall."에서 fall의 품사는?', 'multiple_choice', '["동사(원형부정사)","명사","형용사","부사"]'::jsonb, '동사(원형부정사)', '지각동사 saw 뒤에서 원형부정사로 쓰인 동사입니다.'),
  ('english_grammar', 2, 'advanced', '다음 중 전치사구에 해당하는 것은?', 'multiple_choice', '["in the morning","runs fast","very tall","and yet"]'::jsonb, 'in the morning', '전치사 in이 명사구 the morning과 결합한 전치사구입니다.'),
  ('english_grammar', 2, 'advanced', '"Well, I don''t know."에서 Well의 품사로 가장 적절한 것은?', 'multiple_choice', '["감탄사","부사","형용사","접속사"]'::jsonb, '감탄사', '문장 앞에서 머뭇거림을 나타내는 감탄사로 쓰였습니다.'),
  ('english_grammar', 2, 'advanced', '다음 중 형용사와 부사의 형태가 동일한 단어는?', 'multiple_choice', '["fast","quick","happy","sad"]'::jsonb, 'fast', 'fast는 ''빠른''(형용사)과 ''빠르게''(부사) 형태가 같습니다.'),
  ('english_grammar', 2, 'advanced', '"He backed the car into the garage."에서 backed의 품사는?', 'multiple_choice', '["동사","명사","부사","형용사"]'::jsonb, '동사', '''후진시키다''라는 뜻의 동사로 쓰였습니다.'),
  ('english_grammar', 2, 'advanced', '"I''ll book a table for two."에서 book의 품사를 쓰시오.', 'short_answer', null, '동사', '''예약하다''라는 뜻의 동사로 쓰였습니다.'),
  ('english_grammar', 2, 'advanced', '"The light was too bright."에서 light의 품사를 쓰시오.', 'short_answer', null, '명사', '''빛''이라는 뜻의 명사로 쓰였습니다.'),
  ('english_grammar', 3, 'beginner', '''cat''은 가산명사인가 불가산명사인가?', 'multiple_choice', '["가산명사","불가산명사","둘 다 아님","고유명사"]'::jsonb, '가산명사', 'cat은 수를 셀 수 있는 가산명사입니다.'),
  ('english_grammar', 3, 'beginner', '''water''는 가산명사인가 불가산명사인가?', 'multiple_choice', '["가산명사","불가산명사","둘 다 아님","고유명사"]'::jsonb, '불가산명사', '물질명사인 water는 셀 수 없는 불가산명사입니다.'),
  ('english_grammar', 3, 'beginner', '불가산명사 앞에 쓸 수 없는 것은?', 'multiple_choice', '["a/an","some","the","much"]'::jsonb, 'a/an', '불가산명사는 하나로 셀 수 없어 부정관사 a/an을 쓸 수 없습니다.'),
  ('english_grammar', 3, 'beginner', '다음 중 불가산명사는?', 'multiple_choice', '["money","book","cat","dog"]'::jsonb, 'money', 'money는 셀 수 없는 불가산명사입니다.'),
  ('english_grammar', 3, 'beginner', '복수형을 만들 수 있는 명사는?', 'multiple_choice', '["가산명사","불가산명사","둘 다 안 됨","고유명사만"]'::jsonb, '가산명사', '가산명사만 단수/복수 구분이 가능합니다.'),
  ('english_grammar', 3, 'beginner', '''furniture''는 가산명사인가 불가산명사인가?', 'multiple_choice', '["가산명사","불가산명사","둘 다 아님","고유명사"]'::jsonb, '불가산명사', 'furniture는 대표적인 불가산명사로 복수형이 없습니다.'),
  ('english_grammar', 3, 'beginner', '''coffee''는 가산명사인가 불가산명사인가?', 'short_answer', null, '불가산명사', '물질명사인 coffee는 불가산명사입니다.'),
  ('english_grammar', 3, 'beginner', '''cats''처럼 복수형을 쓸 수 있는 명사는 가산명사인가 불가산명사인가?', 'short_answer', null, '가산명사', '복수형이 있는 명사는 가산명사입니다.'),
  ('english_grammar', 3, 'intermediate', '불가산명사의 수량 표현으로 옳은 것은?', 'multiple_choice', '["a cup of coffee","a coffee","coffees","many coffee"]'::jsonb, 'a cup of coffee', '불가산명사는 단위 명사(a cup of 등)로 수량을 나타냅니다.'),
  ('english_grammar', 3, 'intermediate', '''advice''의 수량 표현으로 옳은 것은?', 'multiple_choice', '["a piece of advice","an advice","advices","some advices"]'::jsonb, 'a piece of advice', 'advice는 불가산명사라 a piece of로 수량을 나타냅니다.'),
  ('english_grammar', 3, 'intermediate', '다음 중 집합명사로 단수·복수 모두 가능한 것은?', 'multiple_choice', '["family","water","money","furniture"]'::jsonb, 'family', 'family는 집합명사로 단수(전체)·복수(구성원) 취급이 모두 가능합니다.'),
  ('english_grammar', 3, 'intermediate', '다음 중 불규칙 복수형이 옳은 것은?', 'multiple_choice', '["child → children","child → childs","man → mans","mouse → mouses"]'::jsonb, 'child → children', 'child의 불규칙 복수형은 children입니다.'),
  ('english_grammar', 3, 'intermediate', '''information''의 특징으로 옳은 것은?', 'multiple_choice', '["불가산명사, 단수 취급","가산명사, 복수형 있음","항상 복수형으로 쓰임","관사 a를 붙여 씀"]'::jsonb, '불가산명사, 단수 취급', 'information은 대표적인 추상 불가산명사입니다.'),
  ('english_grammar', 3, 'intermediate', '''bread''의 수량 표현으로 옳은 것은?', 'multiple_choice', '["a loaf of bread","a bread","breads","many bread"]'::jsonb, 'a loaf of bread', 'bread는 불가산명사라 a loaf of로 수량을 나타냅니다.'),
  ('english_grammar', 3, 'intermediate', '''love''는 가산명사인가 불가산명사인가?', 'short_answer', null, '불가산명사', '추상명사인 love는 불가산명사입니다.'),
  ('english_grammar', 3, 'intermediate', '''child''의 복수형을 쓰시오.', 'short_answer', null, 'children', 'child의 불규칙 복수형은 children입니다.'),
  ('english_grammar', 3, 'advanced', '문맥에 따라 가산·불가산이 모두 가능한 단어는?', 'multiple_choice', '["coffee","furniture","money","equipment"]'::jsonb, 'coffee', 'coffee는 ''음료 종류''일 땐 불가산, ''한 잔''을 의미할 땐 가산으로 쓰입니다.'),
  ('english_grammar', 3, 'advanced', '"I''d like two coffees, please."에서 coffees가 가산명사로 쓰인 이유는?', 'multiple_choice', '["''커피 두 잔''이라는 개별 단위를 의미하므로","coffee는 항상 가산명사이므로","문법적 오류이므로","coffee는 불가산명사로만 쓰이므로"]'::jsonb, '''커피 두 잔''이라는 개별 단위를 의미하므로', '구체적인 잔 단위를 셀 때는 coffee도 가산명사로 쓰입니다.'),
  ('english_grammar', 3, 'advanced', '집합명사가 복수로 취급되는 경우로 옳은 것은?', 'multiple_choice', '["The team are arguing among themselves.","The team is a good one.","Furniture are expensive.","Money are important."]'::jsonb, 'The team are arguing among themselves.', '구성원 개개인의 행동을 강조할 때 집합명사는 복수 취급됩니다.'),
  ('english_grammar', 3, 'advanced', '''evidence''에 대한 설명으로 옳은 것은?', 'multiple_choice', '["불가산명사이며 evidences로 복수형을 쓰지 않는다","가산명사이다","항상 복수형으로 쓰인다","부정관사 a를 붙일 수 있다"]'::jsonb, '불가산명사이며 evidences로 복수형을 쓰지 않는다', 'evidence는 furniture, equipment처럼 대표적인 불가산명사입니다.'),
  ('english_grammar', 3, 'advanced', '다음 중 불규칙 복수형이 아닌 것은?', 'multiple_choice', '["cats","children","men","mice"]'::jsonb, 'cats', 'cats는 규칙적으로 -s를 붙인 복수형입니다.'),
  ('english_grammar', 3, 'advanced', '"There is little information available."에서 little이 쓰인 이유는?', 'multiple_choice', '["information이 불가산명사이기 때문","information이 가산명사이기 때문","little은 가산명사에만 쓰이므로","문법 오류이다"]'::jsonb, 'information이 불가산명사이기 때문', '불가산명사의 양을 나타낼 때 little을 씁니다(가산명사는 few).'),
  ('english_grammar', 3, 'advanced', '''knowledge''는 가산명사인가 불가산명사인가?', 'short_answer', null, '불가산명사', 'knowledge는 대표적인 추상 불가산명사입니다.'),
  ('english_grammar', 3, 'advanced', '"정보가 많다"고 할 때 information과 함께 쓰는 것은 much인가 many인가?', 'short_answer', null, 'much', 'information은 불가산명사이므로 much와 함께 씁니다.'),
  ('english_grammar', 4, 'beginner', '"I saw ___ dog." 빈칸에 알맞은 것은?', 'multiple_choice', '["a","an","the","(관사 없음)"]'::jsonb, 'a', '처음 언급하는 하나의 대상이므로 부정관사 a를 씁니다.'),
  ('english_grammar', 4, 'beginner', '"an ___" 다음에 올 수 있는 단어는?', 'multiple_choice', '["apple","dog","cat","book"]'::jsonb, 'apple', 'apple은 모음 소리로 시작하므로 an을 씁니다.'),
  ('english_grammar', 4, 'beginner', '앞서 언급된 것을 다시 말할 때 쓰는 관사는?', 'multiple_choice', '["a","an","the","관사 없음"]'::jsonb, 'the', '이미 언급되어 특정된 대상에는 정관사 the를 씁니다.'),
  ('english_grammar', 4, 'beginner', '유일한 것을 가리킬 때 쓰는 표현으로 옳은 것은?', 'multiple_choice', '["the sun","a sun","an sun","sun"]'::jsonb, 'the sun', '세상에 하나뿐인 것은 정관사 the와 함께 씁니다.'),
  ('english_grammar', 4, 'beginner', '고유명사 앞에는 보통 관사를 어떻게 쓰는가?', 'multiple_choice', '["관사 없음","a","an","the"]'::jsonb, '관사 없음', '고유명사는 이미 특정된 대상이므로 관사를 쓰지 않습니다.'),
  ('english_grammar', 4, 'beginner', '"She studies ___ math."의 빈칸으로 옳은 것은?', 'multiple_choice', '["(관사 없음)","a","an","the"]'::jsonb, '(관사 없음)', '과목명 math 앞에는 관사를 쓰지 않습니다.'),
  ('english_grammar', 4, 'beginner', '모음 ''소리''로 시작하는 단어 앞에 쓰는 부정관사를 쓰시오.', 'short_answer', null, 'an', 'an hour처럼 모음 소리 앞에는 an을 씁니다.'),
  ('english_grammar', 4, 'beginner', '"I saw a dog. ___ dog was big." 빈칸에 알맞은 관사를 쓰시오.', 'short_answer', null, 'The', '앞에서 언급한 대상을 다시 가리키므로 the를 씁니다.'),
  ('english_grammar', 4, 'intermediate', '다음 중 a를 쓰는 것이 옳은 것은?', 'multiple_choice', '["a university","an university","a hour","an european country"]'::jsonb, 'a university', 'university는 /ju/ 발음(자음 소리)으로 시작해 a를 씁니다.'),
  ('english_grammar', 4, 'intermediate', '다음 중 an을 쓰는 것이 옳은 것은?', 'multiple_choice', '["an hour","a hour","an university","a apple"]'::jsonb, 'an hour', 'hour는 h가 묵음이라 모음 소리로 시작해 an을 씁니다.'),
  ('english_grammar', 4, 'intermediate', '"go to school"과 "go to the school"의 차이로 옳은 것은?', 'multiple_choice', '["전자는 ''공부하러'', 후자는 ''특정 건물에''","의미 차이가 없다","후자만 옳은 표현이다","전자만 옳은 표현이다"]'::jsonb, '전자는 ''공부하러'', 후자는 ''특정 건물에''', '목적으로 쓰인 school은 무관사, 특정 건물을 가리킬 땐 the를 씁니다.'),
  ('english_grammar', 4, 'intermediate', '서수·최상급 앞에 주로 쓰는 관사는?', 'multiple_choice', '["the","a","an","관사 없음"]'::jsonb, 'the', 'the first time, the tallest처럼 서수·최상급 앞엔 the를 씁니다.'),
  ('english_grammar', 4, 'intermediate', '다음 중 무관사가 옳은 것은?', 'multiple_choice', '["He plays soccer.","He plays a soccer.","He plays the soccer.","He plays an soccer."]'::jsonb, 'He plays soccer.', '운동 종목 이름 앞에는 관사를 쓰지 않습니다.'),
  ('english_grammar', 4, 'intermediate', '복수 일반명사 앞의 관사로 옳은 것은?', 'multiple_choice', '["관사 없음","a","an","the(항상)"]'::jsonb, '관사 없음', '일반적인 복수명사는 관사 없이 씁니다.'),
  ('english_grammar', 4, 'intermediate', '"I like ___ coffee."(커피 일반을 의미할 때) 빈칸에 필요한 관사를 쓰시오. 없으면 ''없음''이라고 쓰시오.', 'short_answer', null, '없음', '일반적 의미의 불가산명사는 무관사로 씁니다.'),
  ('english_grammar', 4, 'intermediate', 'u로 시작하지만 발음이 /ju/인 단어(예: university) 앞에 쓰는 관사를 쓰시오.', 'short_answer', null, 'a', '철자가 아닌 발음(자음 소리) 기준이므로 a를 씁니다.'),
  ('english_grammar', 4, 'advanced', '다음 중 관사 사용이 잘못된 것은?', 'multiple_choice', '["I like the coffee. (커피 일반을 의미)","The dog was big.","the first time","the tallest building"]'::jsonb, 'I like the coffee. (커피 일반을 의미)', '일반적 의미의 불가산명사는 the 없이 써야 합니다.'),
  ('english_grammar', 4, 'advanced', '"the rich", "the poor"처럼 "the+형용사"가 의미하는 것은?', 'multiple_choice', '["복수보통명사(그 사람들 전체)","단수명사","불가산명사","형용사 그대로의 의미"]'::jsonb, '복수보통명사(그 사람들 전체)', 'the+형용사는 ''~한 사람들''이라는 복수보통명사로 쓰입니다.'),
  ('english_grammar', 4, 'advanced', '악기 이름 앞의 관사 사용으로 일반적으로 옳은 것은?', 'multiple_choice', '["play the piano","play a piano","play piano","play an piano"]'::jsonb, 'play the piano', '악기 이름 앞에는 보통 정관사 the를 씁니다.'),
  ('english_grammar', 4, 'advanced', '다음 중 관사를 쓰지 않는 것이 옳은 문장은?', 'multiple_choice', '["She studies math.","She studies a math.","She studies the math.","She studies an math."]'::jsonb, 'She studies math.', '과목명 앞에는 관사를 쓰지 않습니다.'),
  ('english_grammar', 4, 'advanced', '"I saw a dog and a cat. ___ dog barked and ___ cat ran away." 빈칸에 공통으로 알맞은 것은?', 'multiple_choice', '["The","A","An","(관사 없음)"]'::jsonb, 'The', '앞에서 언급한 특정 대상을 다시 가리키므로 the를 씁니다.'),
  ('english_grammar', 4, 'advanced', '국가명에 United가 포함될 때 관사 사용으로 옳은 것은?', 'multiple_choice', '["the United States","United States (무관사)","a United States","an United States"]'::jsonb, 'the United States', 'United States처럼 복수형·연합의 의미를 가진 국가명은 the를 붙입니다.'),
  ('english_grammar', 4, 'advanced', '특별한 수식어 없이 쓰는 "He had ___ breakfast before work."의 빈칸에 알맞은 관사를 쓰시오. 없으면 ''없음''이라고 쓰시오.', 'short_answer', null, '없음', '식사 이름 앞에는 보통 관사를 쓰지 않습니다.'),
  ('english_grammar', 4, 'advanced', '악기 이름 앞에 주로 쓰는 관사를 쓰시오.', 'short_answer', null, 'the', 'play the piano처럼 악기 앞에는 the를 씁니다.'),
  ('english_grammar', 5, 'beginner', '''I''의 목적격은?', 'multiple_choice', '["me","my","mine","myself"]'::jsonb, 'me', '주격 I의 목적격은 me입니다.'),
  ('english_grammar', 5, 'beginner', '''he''의 소유격은?', 'multiple_choice', '["his","him","he''s","himself"]'::jsonb, 'his', 'he의 소유격은 his입니다.'),
  ('english_grammar', 5, 'beginner', '"This book is mine."에서 mine은 어떤 대명사인가?', 'multiple_choice', '["소유대명사","인칭대명사","재귀대명사","지시대명사"]'::jsonb, '소유대명사', 'mine은 ''my book''을 대신하는 소유대명사입니다.'),
  ('english_grammar', 5, 'beginner', '가까운 것(단수)을 가리키는 지시대명사는?', 'multiple_choice', '["this","that","these","those"]'::jsonb, 'this', '가까운 단수 대상은 this로 가리킵니다.'),
  ('english_grammar', 5, 'beginner', '"She hurt herself."에서 herself는 어떤 대명사인가?', 'multiple_choice', '["재귀대명사","인칭대명사","소유대명사","지시대명사"]'::jsonb, '재귀대명사', '주어와 목적어가 같아 재귀대명사 herself를 씁니다.'),
  ('english_grammar', 5, 'beginner', '먼 것(복수)을 가리키는 지시대명사는?', 'multiple_choice', '["those","this","that","these"]'::jsonb, 'those', '먼 복수 대상은 those로 가리킵니다.'),
  ('english_grammar', 5, 'beginner', '''they''의 목적격을 쓰시오.', 'short_answer', null, 'them', 'they의 목적격은 them입니다.'),
  ('english_grammar', 5, 'beginner', '''I''의 소유대명사(명사 역할을 하는 형태)를 쓰시오.', 'short_answer', null, 'mine', 'I의 소유대명사는 mine입니다.'),
  ('english_grammar', 5, 'intermediate', '"Would you like ___ coffee?"(권유 의문문) 빈칸에 알맞은 것은?', 'multiple_choice', '["some","any","no","every"]'::jsonb, 'some', '권유·제안의 의문문에서는 any 대신 some을 씁니다.'),
  ('english_grammar', 5, 'intermediate', '강조 용법으로 쓰인 재귀대명사는?', 'multiple_choice', '["The president himself came.","She hurt herself.","I taught myself.","He blamed himself."]'::jsonb, 'The president himself came.', '주어를 강조하는 재귀대명사의 강조 용법입니다.'),
  ('english_grammar', 5, 'intermediate', '부정문·의문문에 주로 쓰이는 부정대명사는?', 'multiple_choice', '["any","some","every","each"]'::jsonb, 'any', 'any는 부정문·의문문에서 주로 쓰입니다.'),
  ('english_grammar', 5, 'intermediate', '''theirs''는 어떤 대명사인가?', 'multiple_choice', '["소유대명사","재귀대명사","지시대명사","인칭대명사"]'::jsonb, '소유대명사', 'theirs는 ''their + 명사''를 대신하는 소유대명사입니다.'),
  ('english_grammar', 5, 'intermediate', 'each와 every의 차이로 옳은 것은?', 'multiple_choice', '["each는 대명사로도 쓰이지만 every는 형용사로만 쓰인다","의미 차이가 없다","every가 대명사이다","each는 형용사로만 쓰인다"]'::jsonb, 'each는 대명사로도 쓰이지만 every는 형용사로만 쓰인다', 'each는 ''each of them''처럼 단독으로도 쓰이지만 every는 항상 명사 앞에 옵니다.'),
  ('english_grammar', 5, 'intermediate', '"neither"의 의미로 옳은 것은?', 'multiple_choice', '["둘 다 아니다","둘 다 그렇다","셋 다 아니다","하나만 그렇다"]'::jsonb, '둘 다 아니다', 'neither는 둘 중 어느 것도 아니라는 부정의 의미입니다.'),
  ('english_grammar', 5, 'intermediate', '"I taught myself."에서 재귀대명사의 용법은 재귀용법인가 강조용법인가?', 'short_answer', null, '재귀용법', '주어의 행동이 자기 자신에게 돌아오는 재귀용법입니다.'),
  ('english_grammar', 5, 'intermediate', '"both"의 의미를 한국어로 쓰시오.', 'short_answer', null, '둘 다', 'both는 ''둘 다''라는 의미의 부정대명사입니다.'),
  ('english_grammar', 5, 'advanced', '재귀용법과 강조용법을 올바르게 구별한 것은?', 'multiple_choice', '["\"She washed herself.\"(재귀) vs \"She herself washed the car.\"(강조)","둘 다 재귀용법이다","둘 다 강조용법이다","구별할 수 없다"]'::jsonb, '"She washed herself."(재귀) vs "She herself washed the car."(강조)', '목적어로 쓰이면 재귀용법, 주어를 강조하면 강조용법입니다.'),
  ('english_grammar', 5, 'advanced', '"either"의 쓰임으로 옳은 것은?', 'multiple_choice', '["You can take either book. (둘 중 하나)","둘 다 아니다","셋 이상 중 하나","전부 다"]'::jsonb, 'You can take either book. (둘 중 하나)', 'either는 둘 중 하나를 의미하는 부정대명사·형용사입니다.'),
  ('english_grammar', 5, 'advanced', '소유격+명사를 대신하는 소유대명사가 옳게 쓰인 것은?', 'multiple_choice', '["This is her book. It''s hers.","This is her book. It''s hers book.","It''s her.","It''s she."]'::jsonb, 'This is her book. It''s hers.', 'hers는 ''her book''을 대신하는 소유대명사로 뒤에 명사를 쓰지 않습니다.'),
  ('english_grammar', 5, 'advanced', '"Would you like some coffee?"처럼 의문문인데 some을 쓰는 이유로 옳은 것은?', 'multiple_choice', '["권유·제안의 의문문이라 긍정 대답을 기대하므로","문법 오류이다","any와 의미가 같아 아무거나 써도 되므로","some은 항상 평서문에만 쓰이므로"]'::jsonb, '권유·제안의 의문문이라 긍정 대답을 기대하므로', '권유 의문문에서는 긍정적 대답을 기대하여 some을 씁니다.'),
  ('english_grammar', 5, 'advanced', '재귀대명사가 올바르게 쓰인 문장은?', 'multiple_choice', '["He introduced himself to the class.","He introduced him to the class.","He introduced he to the class.","He introduced his to the class."]'::jsonb, 'He introduced himself to the class.', '주어와 목적어가 같은 사람이므로 재귀대명사 himself를 씁니다.'),
  ('english_grammar', 5, 'advanced', '뒤에 명사 없이 단독으로 쓰이는 부정대명사는?', 'multiple_choice', '["none","no","every","each other"]'::jsonb, 'none', 'no는 형용사로 명사 앞에 오지만 none은 명사 없이 단독으로 쓰입니다.'),
  ('english_grammar', 5, 'advanced', '"The dog hurt itself."에서 itself의 용법을 쓰시오.', 'short_answer', null, '재귀용법', '주어와 목적어가 같아 재귀용법으로 쓰였습니다.'),
  ('english_grammar', 5, 'advanced', '"either A or B" 구문에서 either의 의미를 쓰시오.', 'short_answer', null, '둘 중 하나', 'either A or B는 ''A 또는 B 둘 중 하나''라는 의미입니다.');
