-- english_grammar question_bank seed — generated from c:/git_repository/5minuate_study/supabase/seed/english_grammar_day06-10.json
-- Supabase SQL 에디터에서 실행하세요 (question_bank 테이블이 먼저 생성되어 있어야 함)

insert into question_bank (curriculum_id, day_num, difficulty, question, type, options, answer, explanation) values
  ('english_grammar', 6, 'beginner', '"I wake up at 7."는 어떤 시제인가?', 'multiple_choice', '["단순현재","현재진행","현재완료","단순과거"]'::jsonb, '단순현재', '습관적으로 반복되는 일이므로 단순현재입니다.'),
  ('english_grammar', 6, 'beginner', '습관이나 반복되는 일을 나타내는 시제는?', 'multiple_choice', '["단순현재","현재진행","현재완료","단순과거"]'::jsonb, '단순현재', '습관, 반복, 사실은 단순현재로 표현합니다.'),
  ('english_grammar', 6, 'beginner', '"She is reading a book now."는 어떤 시제인가?', 'multiple_choice', '["현재진행","단순현재","현재완료","과거진행"]'::jsonb, '현재진행', 'be + V-ing로 지금 진행 중인 동작을 나타냅니다.'),
  ('english_grammar', 6, 'beginner', '3인칭 단수 현재형으로 옳은 것은?', 'multiple_choice', '["He works.","He work.","He working.","He worked."]'::jsonb, 'He works.', '3인칭 단수 현재는 동사에 -s/-es를 붙입니다.'),
  ('english_grammar', 6, 'beginner', '"have/has + p.p." 형태는 어떤 시제인가?', 'multiple_choice', '["현재완료","단순현재","현재진행","과거완료"]'::jsonb, '현재완료', 'have/has + 과거분사는 현재완료 형태입니다.'),
  ('english_grammar', 6, 'beginner', '지금 진행 중인 동작을 나타내는 형태는?', 'multiple_choice', '["be + V-ing","have + p.p.","동사원형","had + p.p."]'::jsonb, 'be + V-ing', '현재진행형은 be동사+V-ing로 만듭니다.'),
  ('english_grammar', 6, 'beginner', '"The Earth moves around the Sun."처럼 변하지 않는 사실을 나타내는 시제를 쓰시오.', 'short_answer', null, '단순현재', '불변의 진리·사실은 단순현재로 씁니다.'),
  ('english_grammar', 6, 'beginner', '현재진행형의 기본 형태를 쓰시오 (be + ___).', 'short_answer', null, 'V-ing', '현재진행형은 be동사 뒤에 V-ing를 붙입니다.'),
  ('english_grammar', 6, 'intermediate', '다음 중 진행형으로 쓸 수 없는 동사는?', 'multiple_choice', '["know","read","eat","run"]'::jsonb, 'know', 'know는 상태동사로 진행형을 쓰지 않습니다.'),
  ('english_grammar', 6, 'intermediate', '"I have been to Paris."는 현재완료의 어떤 용법인가?', 'multiple_choice', '["경험","완료","결과","계속"]'::jsonb, '경험', '''~에 가본 적이 있다''는 경험 용법입니다.'),
  ('english_grammar', 6, 'intermediate', '"She has just finished the work."는 현재완료의 어떤 용법인가?', 'multiple_choice', '["완료","경험","결과","계속"]'::jsonb, '완료', 'just와 함께 쓰여 방금 끝났다는 완료 용법입니다.'),
  ('english_grammar', 6, 'intermediate', '"He has lost his key."(지금도 없음)는 현재완료의 어떤 용법인가?', 'multiple_choice', '["결과","경험","완료","계속"]'::jsonb, '결과', '과거의 동작이 현재까지 영향을 미치는 결과 용법입니다.'),
  ('english_grammar', 6, 'intermediate', '"We have known each other for 10 years."는 현재완료의 어떤 용법인가?', 'multiple_choice', '["계속","경험","완료","결과"]'::jsonb, '계속', 'for와 함께 쓰여 계속 이어짐을 나타내는 계속 용법입니다.'),
  ('english_grammar', 6, 'intermediate', '현재완료와 함께 쓸 수 없는 표현은?', 'multiple_choice', '["yesterday","for","since","already"]'::jsonb, 'yesterday', '현재완료는 특정 과거 시점을 나타내는 yesterday와 함께 쓰지 않습니다.'),
  ('english_grammar', 6, 'intermediate', 'know, believe, love, have(소유), want의 공통적인 특징을 쓰시오.', 'short_answer', null, '상태동사(진행형 불가)', '상태를 나타내는 동사는 진행형으로 쓰지 않습니다.'),
  ('english_grammar', 6, 'intermediate', '특정 과거 시점(yesterday 등)과 함께 쓰지 못하는 시제를 쓰시오.', 'short_answer', null, '현재완료', '현재완료는 특정 과거 시점 표현과 함께 쓰지 않습니다.'),
  ('english_grammar', 6, 'advanced', '"I have been to Paris."는 현재완료의 어떤 용법인가?', 'multiple_choice', '["경험","결과","완료","계속"]'::jsonb, '경험', '''가본 적이 있다''는 경험 용법입니다.'),
  ('english_grammar', 6, 'advanced', '다음 중 어법상 옳은 문장은?', 'multiple_choice', '["I saw him yesterday.","I have seen him yesterday.","I have see him yesterday.","I has seen him yesterday."]'::jsonb, 'I saw him yesterday.', 'yesterday는 특정 과거 시점이므로 단순과거를 씁니다.'),
  ('english_grammar', 6, 'advanced', '"She has been working here since 2020."의 시제는?', 'multiple_choice', '["현재완료진행","현재완료","현재진행","단순현재"]'::jsonb, '현재완료진행', 'have been + V-ing 형태의 현재완료진행형입니다.'),
  ('english_grammar', 6, 'advanced', '상태동사임에도 구어체에서 강조를 위해 예외적으로 진행형처럼 쓰이는 예는?', 'multiple_choice', '["I''m loving it.","I''m knowing it.","I''m believing it.","I''m having it. (소유의 의미)"]'::jsonb, 'I''m loving it.', 'love는 구어체·광고 표현에서 예외적으로 진행형처럼 쓰이기도 합니다.'),
  ('english_grammar', 6, 'advanced', '"He has just finished the work."에서 just의 역할로 옳은 것은?', 'multiple_choice', '["완료를 강조하는 부사","경험을 나타내는 부사","결과를 나타내는 부사","계속을 나타내는 부사"]'::jsonb, '완료를 강조하는 부사', 'just는 ''방금 막''이라는 뜻으로 완료 용법을 강조합니다.'),
  ('english_grammar', 6, 'advanced', '다음 중 현재완료 사용이 어색한 문장은?', 'multiple_choice', '["I have visited Japan last year.","I have visited Japan twice.","I have never visited Japan.","I have just visited Japan."]'::jsonb, 'I have visited Japan last year.', 'last year는 특정 과거 시점이라 현재완료와 함께 쓸 수 없습니다.'),
  ('english_grammar', 6, 'advanced', '"He has lost his key."가 현재완료의 어떤 용법인지 쓰시오.', 'short_answer', null, '결과', '과거의 동작(잃어버림)이 현재까지 영향을 미치는 결과 용법입니다.'),
  ('english_grammar', 6, 'advanced', '현재완료진행형의 형태를 쓰시오 (have/has + ___).', 'short_answer', null, 'been V-ing', '현재완료진행형은 have/has been + V-ing 형태입니다.'),
  ('english_grammar', 7, 'beginner', '"She graduated in 2020."는 어떤 시제인가?', 'multiple_choice', '["단순과거","현재완료","과거진행","과거완료"]'::jsonb, '단순과거', '특정 과거 시점(2020년)에 완료된 일이므로 단순과거입니다.'),
  ('english_grammar', 7, 'beginner', '"I was sleeping when she called."에서 was sleeping은 어떤 시제인가?', 'multiple_choice', '["과거진행","단순과거","과거완료","현재진행"]'::jsonb, '과거진행', 'was/were + V-ing로 과거 특정 시점에 진행 중이던 동작입니다.'),
  ('english_grammar', 7, 'beginner', '"had + p.p." 형태는 어떤 시제인가?', 'multiple_choice', '["과거완료","현재완료","단순과거","미래완료"]'::jsonb, '과거완료', 'had + 과거분사는 과거완료(대과거) 형태입니다.'),
  ('english_grammar', 7, 'beginner', '''go''의 과거형은?', 'multiple_choice', '["went","goed","gone","going"]'::jsonb, 'went', 'go의 불규칙 과거형은 went입니다.'),
  ('english_grammar', 7, 'beginner', '''see''의 과거형은?', 'multiple_choice', '["saw","seed","seen","seeing"]'::jsonb, 'saw', 'see의 불규칙 과거형은 saw입니다.'),
  ('english_grammar', 7, 'beginner', '규칙동사의 과거형 어미는?', 'multiple_choice', '["-ed","-ing","-s","-en"]'::jsonb, '-ed', '규칙동사는 동사원형에 -ed를 붙여 과거형을 만듭니다.'),
  ('english_grammar', 7, 'beginner', '''buy''의 과거형을 쓰시오.', 'short_answer', null, 'bought', 'buy의 불규칙 과거형은 bought입니다.'),
  ('english_grammar', 7, 'beginner', '과거 이전에 일어난 일(대과거)을 나타내는 시제를 쓰시오.', 'short_answer', null, '과거완료', '과거보다 더 이전의 일은 과거완료로 나타냅니다.'),
  ('english_grammar', 7, 'intermediate', '"When I arrived, she had already left."에서 had left가 쓰인 이유는?', 'multiple_choice', '["arrived보다 더 이전에 일어난 일이라서","미래의 일이라서","현재 진행 중이라서","습관이라서"]'::jsonb, 'arrived보다 더 이전에 일어난 일이라서', '과거 기준 시점보다 더 이전의 일에 과거완료를 씁니다.'),
  ('english_grammar', 7, 'intermediate', '진행형(과거진행)과 함께 자주 쓰이는 접속사는?', 'multiple_choice', '["while","when","because","if"]'::jsonb, 'while', 'while은 어떤 일이 진행되는 동안을 나타내 과거진행과 잘 어울립니다.'),
  ('english_grammar', 7, 'intermediate', '"I saw him yesterday."와 "I have seen him before."의 차이로 옳은 것은?', 'multiple_choice', '["전자는 특정 과거 시점, 후자는 경험(현재완료)","의미가 같다","전자만 옳다","후자만 옳다"]'::jsonb, '전자는 특정 과거 시점, 후자는 경험(현재완료)', '단순과거는 특정 시점, 현재완료는 막연한 경험을 나타냅니다.'),
  ('english_grammar', 7, 'intermediate', '다음 중 과거진행형이 옳게 쓰인 것은?', 'multiple_choice', '["I was reading a book at 8 PM.","I readed a book at 8 PM.","I have reading a book.","I read a book now."]'::jsonb, 'I was reading a book at 8 PM.', 'was + V-ing 형태가 올바른 과거진행형입니다.'),
  ('english_grammar', 7, 'intermediate', '시간 순서를 명확히 하기 위해 쓰는 시제는?', 'multiple_choice', '["과거완료","단순현재","현재진행","미래"]'::jsonb, '과거완료', '두 과거 사건의 순서를 명확히 할 때 과거완료를 씁니다.'),
  ('english_grammar', 7, 'intermediate', '다음 중 불규칙 과거형이 아닌 것은?', 'multiple_choice', '["studied","went","saw","bought"]'::jsonb, 'studied', 'studied는 -ed가 붙은 규칙 과거형입니다.'),
  ('english_grammar', 7, 'intermediate', 'when 뒤에 쓰여 짧은 동작을 나타낼 때 주로 쓰는 시제를 쓰시오.', 'short_answer', null, '단순과거', 'when + 단순과거는 짧게 끝난 동작을 나타냅니다.'),
  ('english_grammar', 7, 'intermediate', '"When I arrived, she had already left."에서 두 사건 중 더 먼저 일어난 사건에 쓰인 시제를 쓰시오.', 'short_answer', null, '과거완료', 'arrived보다 먼저 일어난 일이므로 과거완료를 씁니다.'),
  ('english_grammar', 7, 'advanced', '다음 중 시제가 잘못 쓰인 것은?', 'multiple_choice', '["By the time I arrived, the movie had started.","By the time I arrived, the movie has started.","When she called, I was cooking dinner.","I lived in Busan for five years."]'::jsonb, 'By the time I arrived, the movie has started.', '과거 기준 시점(arrived)보다 이전 일이므로 had started가 맞습니다.'),
  ('english_grammar', 7, 'advanced', '"I had been waiting for an hour when the bus finally came."의 시제는?', 'multiple_choice', '["과거완료진행","과거완료","과거진행","현재완료진행"]'::jsonb, '과거완료진행', 'had been + V-ing 형태의 과거완료진행형입니다.'),
  ('english_grammar', 7, 'advanced', '다음 중 while과 함께 쓰기 가장 자연스러운 것은?', 'multiple_choice', '["While I was cooking, the phone rang.","While I cooked, the phone was ringing.","While I have cooked, the phone rang.","While I cook, the phone rang."]'::jsonb, 'While I was cooking, the phone rang.', '진행 중인 동작(과거진행)과 그 사이 일어난 사건(단순과거)의 전형적 결합입니다.'),
  ('english_grammar', 7, 'advanced', '"by the time"과 자주 함께 쓰이는 완료 시제는?', 'multiple_choice', '["과거완료","단순현재","현재완료","미래완료"]'::jsonb, '과거완료', 'by the time + 과거 사건은 과거완료와 자주 쓰입니다.'),
  ('english_grammar', 7, 'advanced', '"I saw him yesterday."를 "I have seen him before."로 바꾸면 의미가 어떻게 달라지는가?', 'multiple_choice', '["특정 과거 시점 → 막연한 과거의 경험으로 바뀐다","의미가 같다","미래의 의미로 바뀐다","진행의 의미로 바뀐다"]'::jsonb, '특정 과거 시점 → 막연한 과거의 경험으로 바뀐다', '단순과거는 특정 시점, 현재완료는 경험을 나타냅니다.'),
  ('english_grammar', 7, 'advanced', '다음 중 과거완료가 불필요하게 쓰인 것은?', 'multiple_choice', '["I had run 10km yesterday.","I was tired because I had run 10km.","She had finished her homework before dinner.","He had already left when I called."]'::jsonb, 'I had run 10km yesterday.', '다른 과거 사건과 비교할 기준이 없으면 단순과거로 충분합니다.'),
  ('english_grammar', 7, 'advanced', '"By the time I arrived, the movie had started."에서 더 먼저 일어난 사건에 쓰인 시제를 쓰시오.', 'short_answer', null, '과거완료', 'arrived보다 먼저 시작된 일이므로 과거완료입니다.'),
  ('english_grammar', 7, 'advanced', '과거완료진행형의 형태를 쓰시오 (had + ___).', 'short_answer', null, 'been V-ing', '과거완료진행형은 had been + V-ing 형태입니다.'),
  ('english_grammar', 8, 'beginner', '"I''ll call you tonight."는 어떤 의미인가?', 'multiple_choice', '["즉흥적 결정","확정된 계획","일정","추측"]'::jsonb, '즉흥적 결정', 'will은 말하는 순간 결정한 일을 나타냅니다.'),
  ('english_grammar', 8, 'beginner', '"I''m going to study abroad next year."는 무엇을 나타내는가?', 'multiple_choice', '["계획·의도","즉흥적 결정","일정","과거 습관"]'::jsonb, '계획·의도', 'be going to는 미리 세운 계획·의도를 나타냅니다.'),
  ('english_grammar', 8, 'beginner', '미래를 나타내는 대표 조동사는?', 'multiple_choice', '["will","must","should","can"]'::jsonb, 'will', 'will은 미래를 나타내는 대표적인 조동사입니다.'),
  ('english_grammar', 8, 'beginner', '"will + ___" 빈칸에 알맞은 것은?', 'multiple_choice', '["동사원형","동명사","과거형","p.p."]'::jsonb, '동사원형', 'will 뒤에는 항상 동사원형이 옵니다.'),
  ('english_grammar', 8, 'beginner', '"The train leaves at 9."는 무엇을 나타내는가?', 'multiple_choice', '["시간표·일정","즉흥적 결정","계획","추측"]'::jsonb, '시간표·일정', '교통·일정은 단순현재로 미래를 나타냅니다.'),
  ('english_grammar', 8, 'beginner', '"We are meeting at 3 PM."은 어떤 형태로 미래를 나타내는가?', 'multiple_choice', '["현재진행","단순현재","현재완료","will"]'::jsonb, '현재진행', '확정된 가까운 미래 계획은 현재진행으로도 나타냅니다.'),
  ('english_grammar', 8, 'beginner', '"It will rain tomorrow."에서 will이 나타내는 것은 예측인가 즉흥적 결정인가?', 'short_answer', null, '예측', 'will은 단순한 미래 예측에도 쓰입니다.'),
  ('english_grammar', 8, 'beginner', 'be going to 다음에 오는 동사의 형태를 쓰시오.', 'short_answer', null, '동사원형', 'be going to 뒤에는 동사원형이 옵니다.'),
  ('english_grammar', 8, 'intermediate', '"The phone is ringing." → "I''ll get it."에서 will이 쓰인 이유는?', 'multiple_choice', '["즉흥적 결정이라서","미리 계획해서","일정이라서","습관이라서"]'::jsonb, '즉흥적 결정이라서', '말하는 순간 즉흥적으로 결정한 일에 will을 씁니다.'),
  ('english_grammar', 8, 'intermediate', '"I''ve decided." → "I''m going to call him."에서 be going to가 쓰인 이유는?', 'multiple_choice', '["이미 결정한 계획이라서","즉흥적이라서","일정표라서","불확실해서"]'::jsonb, '이미 결정한 계획이라서', '이미 마음먹은 계획에는 be going to를 씁니다.'),
  ('english_grammar', 8, 'intermediate', '"Look at those clouds — it''s going to rain."에서 be going to가 쓰인 이유는?', 'multiple_choice', '["현재 상황에 근거한 예측이라서","즉흥적 결정이라서","확정된 일정이라서","과거 습관이라서"]'::jsonb, '현재 상황에 근거한 예측이라서', '눈에 보이는 근거가 있는 예측에는 be going to를 씁니다.'),
  ('english_grammar', 8, 'intermediate', '확정된 가까운 미래 계획을 나타낼 때 쓰는 시제는?', 'multiple_choice', '["현재진행","단순현재","단순과거","현재완료"]'::jsonb, '현재진행', '이미 약속·예약된 가까운 미래는 현재진행으로 나타냅니다.'),
  ('english_grammar', 8, 'intermediate', '"will be + V-ing"는 무엇을 나타내는가?', 'multiple_choice', '["미래진행","미래완료","단순미래","현재완료"]'::jsonb, '미래진행', 'will be + V-ing는 미래 특정 시점에 진행 중일 일을 나타냅니다.'),
  ('english_grammar', 8, 'intermediate', '"will have + p.p."는 무엇을 나타내는가?', 'multiple_choice', '["미래완료","미래진행","단순미래","과거완료"]'::jsonb, '미래완료', 'will have + p.p.는 미래 특정 시점까지 완료될 일을 나타냅니다.'),
  ('english_grammar', 8, 'intermediate', '근거 있는 예측이나 계획을 나타내는 미래 표현을 쓰시오(will 아님).', 'short_answer', null, 'be going to', 'be going to는 근거 있는 예측·계획에 쓰입니다.'),
  ('english_grammar', 8, 'intermediate', '"The train leaves at 9."처럼 시간표를 나타낼 때 쓰는 시제를 쓰시오.', 'short_answer', null, '단순현재', '교통·일정표는 단순현재로 미래를 나타냅니다.'),
  ('english_grammar', 8, 'advanced', 'will과 be going to의 쓰임을 올바르게 구별한 것은?', 'multiple_choice', '["즉흥적 결정엔 will, 미리 세운 계획엔 be going to","항상 서로 바꿔 써도 된다","be going to는 과거에만 쓴다","will은 계획에만 쓴다"]'::jsonb, '즉흥적 결정엔 will, 미리 세운 계획엔 be going to', '결정 시점과 근거 유무로 두 표현을 구별합니다.'),
  ('english_grammar', 8, 'advanced', '"By 8 PM, I will have finished my homework."의 시제는?', 'multiple_choice', '["미래완료","미래진행","단순미래","현재완료"]'::jsonb, '미래완료', 'will have + p.p.는 미래완료 형태입니다.'),
  ('english_grammar', 8, 'advanced', '"This time tomorrow, I will be flying to Paris."의 시제는?', 'multiple_choice', '["미래진행","미래완료","단순미래","현재진행"]'::jsonb, '미래진행', 'will be + V-ing는 미래진행 형태입니다.'),
  ('english_grammar', 8, 'advanced', '다음 중 문법적으로 어색한 문장은?', 'multiple_choice', '["I will going to leave.","The meeting starts at 10 tomorrow.","I''m going to leave now.","She will arrive soon."]'::jsonb, 'I will going to leave.', 'will과 be going to를 함께 쓸 수 없는 중복 오류입니다.'),
  ('english_grammar', 8, 'advanced', '근거 없이 순수하게 예측만 할 때 가장 자연스러운 표현은?', 'multiple_choice', '["It will rain.","It is raining.","It rains.","It has rained."]'::jsonb, 'It will rain.', '특별한 근거 없는 단순 예측은 will로 표현합니다.'),
  ('english_grammar', 8, 'advanced', '다음 중 미래완료진행형이 쓰인 문장은?', 'multiple_choice', '["By next year, she will have been living here for 10 years.","By next year, she will live here.","By next year, she has lived here.","By next year, she lived here."]'::jsonb, 'By next year, she will have been living here for 10 years.', 'will have been + V-ing가 미래완료진행형입니다.'),
  ('english_grammar', 8, 'advanced', '"This time tomorrow, I will be flying to Paris."와 같은 시제 이름을 쓰시오.', 'short_answer', null, '미래진행', 'will be + V-ing 형태의 미래진행형입니다.'),
  ('english_grammar', 8, 'advanced', '미래완료의 형태를 쓰시오 (will + ___).', 'short_answer', null, 'have p.p.', '미래완료는 will have + 과거분사 형태입니다.'),
  ('english_grammar', 9, 'beginner', '현재완료의 형태는?', 'multiple_choice', '["have/has + p.p.","had + p.p.","will have + p.p.","be + p.p."]'::jsonb, 'have/has + p.p.', '현재완료는 have/has + 과거분사입니다.'),
  ('english_grammar', 9, 'beginner', '과거완료의 형태는?', 'multiple_choice', '["had + p.p.","have + p.p.","will have + p.p.","be + p.p."]'::jsonb, 'had + p.p.', '과거완료는 had + 과거분사입니다.'),
  ('english_grammar', 9, 'beginner', '미래완료의 형태는?', 'multiple_choice', '["will have + p.p.","have + p.p.","had + p.p.","will + p.p."]'::jsonb, 'will have + p.p.', '미래완료는 will have + 과거분사입니다.'),
  ('english_grammar', 9, 'beginner', '"He had eaten before I arrived."는 어떤 시제인가?', 'multiple_choice', '["과거완료","현재완료","미래완료","단순과거"]'::jsonb, '과거완료', 'had + p.p. 형태의 과거완료입니다.'),
  ('english_grammar', 9, 'beginner', '"By next year, she will have lived here for 10 years."는 어떤 시제인가?', 'multiple_choice', '["미래완료","현재완료","과거완료","미래진행"]'::jsonb, '미래완료', 'will have + p.p. 형태의 미래완료입니다.'),
  ('english_grammar', 9, 'beginner', '완료 시제를 선택할 때 가장 중요한 기준은?', 'multiple_choice', '["기준 시점이 언제인가","문장의 길이","주어의 인칭","동사의 종류"]'::jsonb, '기준 시점이 언제인가', '완료 시제는 현재/과거/미래 중 어느 기준 시점인지에 따라 정해집니다.'),
  ('english_grammar', 9, 'beginner', '"I have been waiting for 2 hours."는 어떤 시제인가?', 'short_answer', null, '현재완료진행', 'have been + V-ing 형태의 현재완료진행형입니다.'),
  ('english_grammar', 9, 'beginner', '과거완료가 연결하는 두 시점은 ''과거''와 무엇인가?', 'short_answer', null, '과거 이전(대과거)', '과거완료는 과거보다 더 이전 시점을 연결합니다.'),
  ('english_grammar', 9, 'intermediate', '"before, after, when, by the time"과 자주 함께 쓰이는 시제는?', 'multiple_choice', '["과거완료","현재완료","미래완료","단순현재"]'::jsonb, '과거완료', '과거 두 사건의 순서를 나타낼 때 과거완료를 씁니다.'),
  ('english_grammar', 9, 'intermediate', '"by + 미래 시점"과 자주 함께 쓰이는 시제는?', 'multiple_choice', '["미래완료","현재완료","과거완료","단순미래"]'::jsonb, '미래완료', '미래의 기준 시점까지 완료될 일에 미래완료를 씁니다.'),
  ('english_grammar', 9, 'intermediate', '"for, since, already, yet, just, ever, never"와 자주 함께 쓰이는 시제는?', 'multiple_choice', '["현재완료","과거완료","미래완료","단순과거"]'::jsonb, '현재완료', '이 부사(구)들은 현재완료와 자주 함께 쓰입니다.'),
  ('english_grammar', 9, 'intermediate', '현재완료진행형의 의미로 옳은 것은?', 'multiple_choice', '["과거부터 지금까지 계속 진행 중인 동작","과거에 끝난 동작","미래의 계획","현재의 습관"]'::jsonb, '과거부터 지금까지 계속 진행 중인 동작', '현재완료진행은 계속되는 동작을 강조합니다.'),
  ('english_grammar', 9, 'intermediate', '"She will have lived here for 10 years by next year."에서 기준 시점은?', 'multiple_choice', '["미래(next year)","현재","과거","알 수 없음"]'::jsonb, '미래(next year)', 'by next year가 미래완료의 기준 시점입니다.'),
  ('english_grammar', 9, 'intermediate', '"He had eaten before I arrived."에서 기준 시점은?', 'multiple_choice', '["과거(I arrived)","현재","미래","알 수 없음"]'::jsonb, '과거(I arrived)', 'I arrived라는 과거 시점이 기준입니다.'),
  ('english_grammar', 9, 'intermediate', '''과거부터 지금까지 계속''을 나타내는 완료진행형을 쓰시오.', 'short_answer', null, '현재완료진행', 'have been + V-ing 형태입니다.'),
  ('english_grammar', 9, 'intermediate', '"by the time"과 문맥상 과거 기준으로 잘 어울리는 완료 시제를 쓰시오.', 'short_answer', null, '과거완료', 'by the time + 과거 사건은 과거완료와 자주 쓰입니다.'),
  ('english_grammar', 9, 'advanced', '다음 중 시제 선택이 옳은 것은?', 'multiple_choice', '["By the time she gets home, I will have cooked dinner.","By the time she gets home, I have cooked dinner.","By the time she gets home, I had cooked dinner.","By the time she gets home, I cook dinner."]'::jsonb, 'By the time she gets home, I will have cooked dinner.', '미래 기준 시점까지 완료될 일이므로 미래완료가 맞습니다.'),
  ('english_grammar', 9, 'advanced', '"I have been waiting for 2 hours and I''m still waiting."를 가장 잘 나타내는 시제는?', 'multiple_choice', '["현재완료진행","현재완료","현재진행","과거완료진행"]'::jsonb, '현재완료진행', '지금까지 계속되는 동작을 강조하는 현재완료진행이 적절합니다.'),
  ('english_grammar', 9, 'advanced', '과거완료와 단순과거를 혼용해 시간 순서가 가장 명확한 문장은?', 'multiple_choice', '["After he had finished his homework, he went to bed.","After he finished his homework, he had gone to bed.","He went to bed after he goes to bed.","He had went to bed."]'::jsonb, 'After he had finished his homework, he went to bed.', '먼저 일어난 일(숙제)에 과거완료, 나중 일(잠)에 단순과거를 써 순서가 명확합니다.'),
  ('english_grammar', 9, 'advanced', '미래완료진행형의 형태로 옳은 것은?', 'multiple_choice', '["will have been + V-ing","will be + V-ing","will have + p.p.","have been + V-ing"]'::jsonb, 'will have been + V-ing', '미래완료진행형은 will have been + V-ing 형태입니다.'),
  ('english_grammar', 9, 'advanced', '현재완료·과거완료·미래완료의 공통점으로 옳은 것은?', 'multiple_choice', '["어떤 기준 시점 이전에 일이 끝나거나 계속됨을 나타낸다","모두 과거의 일만 나타낸다","모두 미래의 일만 나타낸다","기준 시점이 없다"]'::jsonb, '어떤 기준 시점 이전에 일이 끝나거나 계속됨을 나타낸다', '세 완료 시제 모두 기준 시점을 중심으로 완료·계속을 나타냅니다.'),
  ('english_grammar', 9, 'advanced', '완료 시제와 기준 시점이 바르게 짝지어지지 않은 것은?', 'multiple_choice', '["과거완료 - 현재","과거완료 - 과거 이전 시점","미래완료 - 미래 시점","현재완료 - 현재"]'::jsonb, '과거완료 - 현재', '과거완료의 기준 시점은 현재가 아니라 과거입니다.'),
  ('english_grammar', 9, 'advanced', '"By the time she gets home, I will have cooked dinner."에서 쓰인 완료 시제를 쓰시오.', 'short_answer', null, '미래완료', 'will have + p.p. 형태의 미래완료입니다.'),
  ('english_grammar', 9, 'advanced', '완료진행형이 강조하는 것은 완료인가 계속(진행)인가?', 'short_answer', null, '계속(진행)', '완료진행형은 동작이 계속되고 있음을 강조합니다.'),
  ('english_grammar', 10, 'beginner', '"She can speak three languages."에서 can의 의미는?', 'multiple_choice', '["능력","허가","의무","추측"]'::jsonb, '능력', 'can은 ''~할 수 있다''는 능력을 나타냅니다.'),
  ('english_grammar', 10, 'beginner', '"Can I borrow your pen?"에서 can의 의미는?', 'multiple_choice', '["허가","능력","의무","추측"]'::jsonb, '허가', '비공식적인 허가를 구할 때 can을 씁니다.'),
  ('english_grammar', 10, 'beginner', '"May I come in?"에서 may의 의미는?', 'multiple_choice', '["허가(공식)","능력","의무","추측"]'::jsonb, '허가(공식)', 'may는 can보다 공식적인 허가를 나타냅니다.'),
  ('english_grammar', 10, 'beginner', '"You must wear a seatbelt."에서 must의 의미는?', 'multiple_choice', '["강한 의무","허가","능력","약한 충고"]'::jsonb, '강한 의무', 'must는 강한 의무(~해야 한다)를 나타냅니다.'),
  ('english_grammar', 10, 'beginner', '"You should see a doctor."에서 should의 의미는?', 'multiple_choice', '["약한 의무·충고","강한 의무","허가","능력"]'::jsonb, '약한 의무·충고', 'should는 must보다 약한 의무·충고를 나타냅니다.'),
  ('english_grammar', 10, 'beginner', 'can의 과거형은?', 'multiple_choice', '["could","canned","can''d","cans"]'::jsonb, 'could', 'can의 과거형은 could입니다.'),
  ('english_grammar', 10, 'beginner', 'must not의 의미를 쓰시오.', 'short_answer', null, '금지', 'must not은 ''~하면 안 된다''는 금지를 나타냅니다.'),
  ('english_grammar', 10, 'beginner', 'don''t have to의 의미를 쓰시오.', 'short_answer', null, '불필요(할 필요 없음)', 'don''t have to는 ''~할 필요가 없다''는 불필요를 나타냅니다.'),
  ('english_grammar', 10, 'intermediate', '"It may rain tonight."에서 may의 의미로 옳은 것은?', 'multiple_choice', '["가능성(50%)","허가","의무","능력"]'::jsonb, '가능성(50%)', 'may는 약 50% 정도의 가능성을 나타냅니다.'),
  ('english_grammar', 10, 'intermediate', '"He must be tired."에서 must의 의미로 옳은 것은?', 'multiple_choice', '["강한 추론(~임에 틀림없다)","강한 의무","허가","금지"]'::jsonb, '강한 추론(~임에 틀림없다)', 'must는 사람에 대한 강한 추측(추론)에도 쓰입니다.'),
  ('english_grammar', 10, 'intermediate', 'might은 어떤 조동사의 과거형인가?', 'multiple_choice', '["may","can","must","should"]'::jsonb, 'may', 'might은 may의 과거형이며 낮은 가능성을 나타냅니다.'),
  ('english_grammar', 10, 'intermediate', 'could의 용법으로 옳지 않은 것은?', 'multiple_choice', '["강한 의무","can의 과거형","공손한 요청","낮은 가능성"]'::jsonb, '강한 의무', 'could는 강한 의무를 나타내지 않습니다.'),
  ('english_grammar', 10, 'intermediate', 'ought to와 유사한 의미의 조동사는?', 'multiple_choice', '["should","must","can","may"]'::jsonb, 'should', 'ought to는 should와 유사하게 도덕적 의무를 나타냅니다.'),
  ('english_grammar', 10, 'intermediate', 'must not과 don''t have to의 의미 차이로 옳은 것은?', 'multiple_choice', '["must not은 금지, don''t have to는 불필요","의미가 같다","must not이 더 약하다","don''t have to가 금지다"]'::jsonb, 'must not은 금지, don''t have to는 불필요', 'must not(금지)과 don''t have to(불필요)는 의미가 다릅니다.'),
  ('english_grammar', 10, 'intermediate', '"It may rain tonight."을 가능성이 더 낮음을 나타내는 문장으로 바꿔 쓰시오.', 'short_answer', null, 'It might rain tonight.', 'might은 may보다 낮은 가능성을 나타냅니다.'),
  ('english_grammar', 10, 'intermediate', '공손한 요청을 나타낼 때 can 대신 쓸 수 있는 조동사를 쓰시오.', 'short_answer', null, 'could', 'could는 can보다 더 공손한 요청을 나타냅니다.'),
  ('english_grammar', 10, 'advanced', '다음 중 must의 의미가 다른 하나는?', 'multiple_choice', '["He must be at home.","You must wear a seatbelt.","You must not smoke here.","Students must submit the form."]'::jsonb, 'He must be at home.', '이것만 강한 추론이고 나머지는 의무를 나타냅니다.'),
  ('english_grammar', 10, 'advanced', '다음 중 가능성의 정도가 가장 낮은 것은?', 'multiple_choice', '["might","may","must","will"]'::jsonb, 'might', 'might은 may보다도 낮은, 불확실한 가능성을 나타냅니다.'),
  ('english_grammar', 10, 'advanced', '"You don''t have to come if you''re busy."의 의미로 옳은 것은?', 'multiple_choice', '["올 필요가 없다(선택)","오면 안 된다(금지)","반드시 와야 한다","올 수 없다"]'::jsonb, '올 필요가 없다(선택)', 'don''t have to는 금지가 아니라 불필요·선택을 나타냅니다.'),
  ('english_grammar', 10, 'advanced', '"Could I borrow your car?"가 "Can I borrow your car?"보다 더 공손한 이유는?', 'multiple_choice', '["could가 더 격식 있고 완곡한 표현이라서","could는 과거의 의미만 있어서","can은 허가에 쓰이지 않아서","의미 차이가 없어서"]'::jsonb, 'could가 더 격식 있고 완곡한 표현이라서', 'could는 can보다 완곡하고 공손하게 느껴집니다.'),
  ('english_grammar', 10, 'advanced', '다음 중 문맥상 옳은 것은?', 'multiple_choice', '["You must not park here.","You don''t must park here.","You not must park here.","You mustn''t to park here."]'::jsonb, 'You must not park here.', 'must not이 올바른 금지 표현이며 뒤에 to를 쓰지 않습니다.'),
  ('english_grammar', 10, 'advanced', 'should와 must의 의무 강도를 비교했을 때 옳은 것은?', 'multiple_choice', '["must가 should보다 더 강한 의무","should가 더 강하다","강도가 같다","비교 불가"]'::jsonb, 'must가 should보다 더 강한 의무', 'must는 강한 의무, should는 약한 의무·충고입니다.'),
  ('english_grammar', 10, 'advanced', '허가를 나타내는 공식적인 조동사를 can/may 중에서 쓰시오.', 'short_answer', null, 'may', 'may가 can보다 더 공식적인 허가를 나타냅니다.'),
  ('english_grammar', 10, 'advanced', '충고를 나타내는 대표적인 조동사를 쓰시오.', 'short_answer', null, 'should', 'should는 대표적인 충고·의무의 조동사입니다.');
