-- english_vocab question_bank seed — generated from c:/git_repository/5minuate_study/supabase/seed/english_vocab_day01-05.json
-- Supabase SQL 에디터에서 실행하세요 (question_bank 테이블이 먼저 생성되어 있어야 함)

insert into question_bank (curriculum_id, day_num, difficulty, question, type, options, answer, explanation) values
  ('english_vocab', 1, 'beginner', '''achieve''의 뜻으로 알맞은 것은?', 'multiple_choice', '["성취하다","빌리다","배달하다","조사하다"]'::jsonb, '성취하다', 'achieve는 ''성취하다, 이루다''라는 뜻입니다.'),
  ('english_vocab', 1, 'beginner', '''borrow''의 뜻으로 알맞은 것은?', 'multiple_choice', '["빌리다","완료하다","모으다","유지하다"]'::jsonb, '빌리다', 'borrow는 ''빌리다''라는 뜻입니다.'),
  ('english_vocab', 1, 'beginner', '''complete''의 뜻으로 알맞은 것은?', 'multiple_choice', '["완료하다","조사하다","배달하다","준비하다"]'::jsonb, '완료하다', 'complete는 ''완료하다''라는 뜻입니다.'),
  ('english_vocab', 1, 'beginner', '''deliver''의 뜻으로 알맞은 것은?', 'multiple_choice', '["배달하다","돕다","성취하다","모으다"]'::jsonb, '배달하다', 'deliver는 ''배달하다, 전달하다''라는 뜻입니다.'),
  ('english_vocab', 1, 'beginner', '''examine''의 뜻으로 알맞은 것은?', 'multiple_choice', '["조사하다","유지하다","준비하다","빌리다"]'::jsonb, '조사하다', 'examine은 ''조사하다, 검사하다''라는 뜻입니다.'),
  ('english_vocab', 1, 'beginner', '''maintain''의 뜻으로 알맞은 것은?', 'multiple_choice', '["유지하다","완료하다","돕다","모으다"]'::jsonb, '유지하다', 'maintain은 ''유지하다''라는 뜻입니다.'),
  ('english_vocab', 1, 'beginner', '''assist''의 뜻을 한 단어로 쓰시오.', 'short_answer', null, '돕다', 'assist는 ''돕다''라는 뜻입니다.'),
  ('english_vocab', 1, 'beginner', '''gather''의 뜻을 한 단어로 쓰시오.', 'short_answer', null, '모으다', 'gather는 ''모으다''라는 뜻입니다.'),
  ('english_vocab', 1, 'intermediate', '"She ___ her goal after years of effort." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["achieved","borrowed","examined","delivered"]'::jsonb, 'achieved', 'achieve는 ''성취하다''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 1, 'intermediate', '"Let''s ___ a meeting for next week." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["arrange","gather","maintain","examine"]'::jsonb, 'arrange', 'arrange는 ''준비하다, 마련하다''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 1, 'intermediate', '"May I ___ your pen?" 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["borrow","deliver","complete","assist"]'::jsonb, 'borrow', 'borrow는 ''빌리다''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 1, 'intermediate', '"I ___ my homework before dinner." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["completed","borrowed","examined","arranged"]'::jsonb, 'completed', 'complete는 ''완료하다''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 1, 'intermediate', '"The doctor ___ the patient carefully." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["examined","delivered","achieved","gathered"]'::jsonb, 'examined', 'examine은 ''조사하다, 진찰하다''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 1, 'intermediate', '"It''s hard to ___ good habits." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["maintain","borrow","complete","assist"]'::jsonb, 'maintain', 'maintain은 ''유지하다''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 1, 'intermediate', '"They ___ food quickly in this city." 빈칸에 들어갈 단어를 쓰시오. (배달하다)', 'short_answer', null, 'deliver', 'deliver는 ''배달하다''라는 뜻입니다.'),
  ('english_vocab', 1, 'intermediate', '"We ___ information for the report." 빈칸에 들어갈 단어를 쓰시오. (모으다, 과거형)', 'short_answer', null, 'gathered', 'gather의 과거형 gathered가 알맞습니다.'),
  ('english_vocab', 1, 'advanced', '다음 중 의미가 나머지 셋과 가장 다른 것은?', 'multiple_choice', '["achieve","accomplish","complete","borrow"]'::jsonb, 'borrow', 'achieve, accomplish, complete는 ''이루다/끝내다''의 의미이지만 borrow는 ''빌리다''라는 다른 의미입니다.'),
  ('english_vocab', 1, 'advanced', '''examine''과 의미가 가장 가까운 단어는?', 'multiple_choice', '["inspect","deliver","maintain","arrange"]'::jsonb, 'inspect', 'examine과 inspect는 모두 ''조사하다, 검사하다''라는 뜻입니다.'),
  ('english_vocab', 1, 'advanced', '"We need to ___ enough evidence before we proceed." 문맥상 가장 적절한 것은?', 'multiple_choice', '["gather","borrow","deliver","achieve"]'::jsonb, 'gather', 'gather는 ''모으다''라는 뜻으로 증거를 모은다는 문맥에 맞습니다.'),
  ('english_vocab', 1, 'advanced', '''돕다''라는 뜻을 가진 단어는?', 'multiple_choice', '["assist","examine","maintain","complete"]'::jsonb, 'assist', 'assist는 ''돕다''라는 뜻입니다.'),
  ('english_vocab', 1, 'advanced', '"He worked hard to ___ his dream." 문맥상 가장 적절한 것은?', 'multiple_choice', '["achieve","borrow","deliver","examine"]'::jsonb, 'achieve', 'achieve는 ''이루다, 성취하다''라는 뜻으로 꿈을 이룬다는 문맥에 맞습니다.'),
  ('english_vocab', 1, 'advanced', '"to ___ a meeting"과 같이 쓰이는 단어로 가장 적절한 것은?', 'multiple_choice', '["arrange","borrow","examine","achieve"]'::jsonb, 'arrange', 'arrange a meeting은 ''회의를 준비하다, 마련하다''라는 뜻의 표현입니다.'),
  ('english_vocab', 1, 'advanced', '''유지하다, 지속하다''라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'maintain', 'maintain은 ''유지하다, 지속하다''라는 뜻입니다.'),
  ('english_vocab', 1, 'advanced', '''준비하다, 마련하다''라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'arrange', 'arrange는 ''준비하다, 마련하다''라는 뜻입니다.'),
  ('english_vocab', 2, 'beginner', '''assume''의 뜻으로 알맞은 것은?', 'multiple_choice', '["추측하다","믿다","고려하다","의심하다"]'::jsonb, '추측하다', 'assume은 ''추측하다, 가정하다''라는 뜻입니다.'),
  ('english_vocab', 2, 'beginner', '''believe''의 뜻으로 알맞은 것은?', 'multiple_choice', '["믿다","후회하다","상상하다","깨닫다"]'::jsonb, '믿다', 'believe는 ''믿다''라는 뜻입니다.'),
  ('english_vocab', 2, 'beginner', '''consider''의 뜻으로 알맞은 것은?', 'multiple_choice', '["고려하다","의심하다","예상하다","추정하다"]'::jsonb, '고려하다', 'consider는 ''고려하다''라는 뜻입니다.'),
  ('english_vocab', 2, 'beginner', '''doubt''의 뜻으로 알맞은 것은?', 'multiple_choice', '["의심하다","믿다","상상하다","인정하다"]'::jsonb, '의심하다', 'doubt는 ''의심하다''라는 뜻입니다.'),
  ('english_vocab', 2, 'beginner', '''expect''의 뜻으로 알맞은 것은?', 'multiple_choice', '["예상하다","후회하다","추측하다","깨닫다"]'::jsonb, '예상하다', 'expect는 ''예상하다, 기대하다''라는 뜻입니다.'),
  ('english_vocab', 2, 'beginner', '''imagine''의 뜻으로 알맞은 것은?', 'multiple_choice', '["상상하다","고려하다","의심하다","추정하다"]'::jsonb, '상상하다', 'imagine은 ''상상하다''라는 뜻입니다.'),
  ('english_vocab', 2, 'beginner', '''recognize''의 뜻을 한 단어로 쓰시오.', 'short_answer', null, '알아보다', 'recognize는 ''알아보다, 인정하다''라는 뜻입니다.'),
  ('english_vocab', 2, 'beginner', '''realize''의 뜻을 한 단어로 쓰시오.', 'short_answer', null, '깨닫다', 'realize는 ''깨닫다''라는 뜻입니다.'),
  ('english_vocab', 2, 'intermediate', '"I have no real evidence, so I can only ___ that you''re right." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["assume","doubt","regret","recognize"]'::jsonb, 'assume', '증거가 없어 ''추측할'' 수밖에 없다는 문맥이므로 assume이 알맞습니다.'),
  ('english_vocab', 2, 'intermediate', '"I ___ in her ability to succeed." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["believe","consider","suppose","realize"]'::jsonb, 'believe', 'believe in은 ''~을 믿다''라는 뜻입니다.'),
  ('english_vocab', 2, 'intermediate', '"Please ___ my opinion before deciding." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["consider","doubt","expect","imagine"]'::jsonb, 'consider', 'consider는 ''고려하다''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 2, 'intermediate', '"He has broken every promise before, so I seriously ___ he will come to the party." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["doubt","believe","recognize","regret"]'::jsonb, 'doubt', '약속을 계속 어겨온 사람이라는 문맥이므로 ''의심하다''라는 뜻의 doubt가 알맞습니다.'),
  ('english_vocab', 2, 'intermediate', '"We ___ good results from this plan." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["expect","assume","suppose","realize"]'::jsonb, 'expect', 'expect는 ''예상하다, 기대하다''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 2, 'intermediate', '"___ a world without conflict." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["Imagine","Consider","Doubt","Regret"]'::jsonb, 'Imagine', 'imagine은 ''상상하다''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 2, 'intermediate', '"I ___ her voice immediately." 빈칸에 들어갈 단어를 쓰시오. (알아보다, 과거형)', 'short_answer', null, 'recognized', 'recognize의 과거형 recognized가 알맞습니다.'),
  ('english_vocab', 2, 'intermediate', '"He ___ his decision." 빈칸에 들어갈 단어를 쓰시오. (후회하다, 3인칭 단수 현재)', 'short_answer', null, 'regrets', 'regret의 3인칭 단수형 regrets가 알맞습니다.'),
  ('english_vocab', 2, 'advanced', '다음 중 의미가 나머지 셋과 가장 다른 것은?', 'multiple_choice', '["doubt","believe","assume","suppose"]'::jsonb, 'doubt', 'believe, assume, suppose는 모두 긍정적인 추측을 뜻하지만 doubt는 ''의심하다''라는 반대 의미입니다.'),
  ('english_vocab', 2, 'advanced', '''realize''와 의미가 가장 가까운 단어는?', 'multiple_choice', '["recognize","doubt","regret","expect"]'::jsonb, 'recognize', '둘 다 ''깨닫다, 인식하다''라는 의미로 쓰일 수 있습니다.'),
  ('english_vocab', 2, 'advanced', '"It wasn''t until the results came back that I finally ___ I had made a mistake." 문맥상 가장 적절한 것은?', 'multiple_choice', '["realized","expected","doubted","considered"]'::jsonb, 'realized', '''finally realized''는 ''마침내 깨달았다''라는 뜻의 자연스러운 표현입니다.'),
  ('english_vocab', 2, 'advanced', '''후회하다''라는 뜻을 가진 단어는?', 'multiple_choice', '["regret","imagine","suppose","recognize"]'::jsonb, 'regret', 'regret은 ''후회하다''라는 뜻입니다.'),
  ('english_vocab', 2, 'advanced', '"I ___ that you are tired after the long trip." 문맥상 가장 적절한 것은?', 'multiple_choice', '["suppose","doubt","regret","recognize"]'::jsonb, 'suppose', 'suppose는 ''추정하다''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 2, 'advanced', '다음 중 ''생각하다, 추측하다'' 계열이 아닌 것은?', 'multiple_choice', '["recognize","assume","suppose","believe"]'::jsonb, 'recognize', 'recognize는 ''알아보다, 인식하다''로 나머지와 결이 다릅니다.'),
  ('english_vocab', 2, 'advanced', '''고려하다, 숙고하다''라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'consider', 'consider는 ''고려하다''라는 뜻입니다.'),
  ('english_vocab', 2, 'advanced', '''예상하다, 기대하다''라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'expect', 'expect는 ''예상하다, 기대하다''라는 뜻입니다.'),
  ('english_vocab', 3, 'beginner', '''ancient''의 뜻으로 알맞은 것은?', 'multiple_choice', '["고대의","간단한","복잡한","평범한"]'::jsonb, '고대의', 'ancient는 ''고대의''라는 뜻입니다.'),
  ('english_vocab', 3, 'beginner', '''brief''의 뜻으로 알맞은 것은?', 'multiple_choice', '["간단한","거대한","정확한","생생한"]'::jsonb, '간단한', 'brief는 ''간단한, 짧은''이라는 뜻입니다.'),
  ('english_vocab', 3, 'beginner', '''complex''의 뜻으로 알맞은 것은?', 'multiple_choice', '["복잡한","부서지기 쉬운","점진적인","필수적인"]'::jsonb, '복잡한', 'complex는 ''복잡한''이라는 뜻입니다.'),
  ('english_vocab', 3, 'beginner', '''essential''의 뜻으로 알맞은 것은?', 'multiple_choice', '["필수적인","평범한","정확한","거대한"]'::jsonb, '필수적인', 'essential은 ''필수적인''이라는 뜻입니다.'),
  ('english_vocab', 3, 'beginner', '''fragile''의 뜻으로 알맞은 것은?', 'multiple_choice', '["부서지기 쉬운","고대의","간단한","생생한"]'::jsonb, '부서지기 쉬운', 'fragile은 ''부서지기 쉬운''이라는 뜻입니다.'),
  ('english_vocab', 3, 'beginner', '''immense''의 뜻으로 알맞은 것은?', 'multiple_choice', '["거대한","평범한","정확한","점진적인"]'::jsonb, '거대한', 'immense는 ''거대한, 엄청난''이라는 뜻입니다.'),
  ('english_vocab', 3, 'beginner', '''gradual''의 뜻을 한 단어로 쓰시오.', 'short_answer', null, '점진적인', 'gradual은 ''점진적인''이라는 뜻입니다.'),
  ('english_vocab', 3, 'beginner', '''vivid''의 뜻을 한 단어로 쓰시오.', 'short_answer', null, '생생한', 'vivid는 ''생생한''이라는 뜻입니다.'),
  ('english_vocab', 3, 'intermediate', '"That is an ___ civilization from thousands of years ago." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["ancient","brief","ordinary","precise"]'::jsonb, 'ancient', 'ancient는 ''고대의''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 3, 'intermediate', '"He gave a ___ explanation before leaving." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["brief","immense","fragile","gradual"]'::jsonb, 'brief', 'brief는 ''간단한''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 3, 'intermediate', '"This is a ___ problem with no easy solution." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["complex","ordinary","vivid","precise"]'::jsonb, 'complex', 'complex는 ''복잡한''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 3, 'intermediate', '"Water is ___ for life." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["essential","fragile","ancient","brief"]'::jsonb, 'essential', 'essential은 ''필수적인''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 3, 'intermediate', '"Handle the glass carefully; it''s ___." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["fragile","immense","gradual","complex"]'::jsonb, 'fragile', 'fragile은 ''부서지기 쉬운''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 3, 'intermediate', '"Give me the ___ time, please." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["precise","vivid","ordinary","essential"]'::jsonb, 'precise', 'precise는 ''정확한''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 3, 'intermediate', '"It was just an ___ day, nothing special." 빈칸에 들어갈 단어를 쓰시오. (평범한)', 'short_answer', null, 'ordinary', 'ordinary는 ''평범한''이라는 뜻입니다.'),
  ('english_vocab', 3, 'intermediate', '"She has a ___ memory of that summer." 빈칸에 들어갈 단어를 쓰시오. (생생한)', 'short_answer', null, 'vivid', 'vivid는 ''생생한''이라는 뜻입니다.'),
  ('english_vocab', 3, 'advanced', '다음 중 의미가 나머지 셋과 가장 다른 것은?', 'multiple_choice', '["immense","huge","vast","brief"]'::jsonb, 'brief', 'immense, huge, vast는 모두 ''거대한''이라는 뜻이지만 brief는 ''짧은, 간단한''이라는 반대 성격의 의미입니다.'),
  ('english_vocab', 3, 'advanced', '''precise''와 의미가 가장 가까운 단어는?', 'multiple_choice', '["accurate","vivid","fragile","gradual"]'::jsonb, 'accurate', 'precise와 accurate는 모두 ''정확한''이라는 뜻입니다.'),
  ('english_vocab', 3, 'advanced', '"The change happened so ___ that no one noticed at first." 문맥상 가장 적절한 것은?', 'multiple_choice', '["gradually","precisely","vividly","ordinarily"]'::jsonb, 'gradually', 'gradually는 ''점진적으로''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 3, 'advanced', '''부서지기 쉬운''이라는 뜻을 가진 단어는?', 'multiple_choice', '["fragile","essential","complex","ancient"]'::jsonb, 'fragile', 'fragile은 ''부서지기 쉬운''이라는 뜻입니다.'),
  ('english_vocab', 3, 'advanced', '"The task required an ___ amount of effort." 문맥상 가장 적절한 것은?', 'multiple_choice', '["immense","brief","precise","ordinary"]'::jsonb, 'immense', 'immense는 ''거대한, 엄청난''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 3, 'advanced', '다음 중 ''평범한, 일상적인''이라는 뜻을 가진 단어는?', 'multiple_choice', '["ordinary","vivid","immense","precise"]'::jsonb, 'ordinary', 'ordinary는 ''평범한, 일상적인''이라는 뜻입니다.'),
  ('english_vocab', 3, 'advanced', '''필수적인, 근본적인''이라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'essential', 'essential은 ''필수적인''이라는 뜻입니다.'),
  ('english_vocab', 3, 'advanced', '''정확한''이라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'precise', 'precise는 ''정확한''이라는 뜻입니다.'),
  ('english_vocab', 4, 'beginner', '''anxious''의 뜻으로 알맞은 것은?', 'multiple_choice', '["불안한","감사하는","호기심 많은","열망하는"]'::jsonb, '불안한', 'anxious는 ''불안한''이라는 뜻입니다.'),
  ('english_vocab', 4, 'beginner', '''ashamed''의 뜻으로 알맞은 것은?', 'multiple_choice', '["부끄러운","화난","안도한","질투하는"]'::jsonb, '부끄러운', 'ashamed는 ''부끄러운''이라는 뜻입니다.'),
  ('english_vocab', 4, 'beginner', '''curious''의 뜻으로 알맞은 것은?', 'multiple_choice', '["호기심 많은","불안한","긴장한","슬픈"]'::jsonb, '호기심 많은', 'curious는 ''호기심 많은''이라는 뜻입니다.'),
  ('english_vocab', 4, 'beginner', '''eager''의 뜻으로 알맞은 것은?', 'multiple_choice', '["열망하는","부끄러운","화난","안도한"]'::jsonb, '열망하는', 'eager는 ''열망하는''이라는 뜻입니다.'),
  ('english_vocab', 4, 'beginner', '''furious''의 뜻으로 알맞은 것은?', 'multiple_choice', '["몹시 화난","감사하는","질투하는","긴장한"]'::jsonb, '몹시 화난', 'furious는 ''몹시 화난''이라는 뜻입니다.'),
  ('english_vocab', 4, 'beginner', '''grateful''의 뜻으로 알맞은 것은?', 'multiple_choice', '["감사하는","불안한","슬픈","호기심 많은"]'::jsonb, '감사하는', 'grateful은 ''감사하는''이라는 뜻입니다.'),
  ('english_vocab', 4, 'beginner', '''jealous''의 뜻을 한 단어로 쓰시오.', 'short_answer', null, '질투하는', 'jealous는 ''질투하는''이라는 뜻입니다.'),
  ('english_vocab', 4, 'beginner', '''nervous''의 뜻을 한 단어로 쓰시오.', 'short_answer', null, '긴장한', 'nervous는 ''긴장한''이라는 뜻입니다.'),
  ('english_vocab', 4, 'intermediate', '"She felt ___ before the exam." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["anxious","grateful","eager","relieved"]'::jsonb, 'anxious', 'anxious는 ''불안한''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 4, 'intermediate', '"He was ___ of his mistake." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["ashamed","curious","furious","jealous"]'::jsonb, 'ashamed', 'ashamed는 ''부끄러운''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 4, 'intermediate', '"The child was ___ about everything." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["curious","nervous","sorrowful","ashamed"]'::jsonb, 'curious', 'curious는 ''호기심 많은''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 4, 'intermediate', '"She was ___ to learn new things." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["eager","furious","relieved","ashamed"]'::jsonb, 'eager', 'eager는 ''열망하는''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 4, 'intermediate', '"He was ___ about the delay." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["furious","grateful","curious","eager"]'::jsonb, 'furious', 'furious는 ''몹시 화난''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 4, 'intermediate', '"I''m ___ for your help." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["grateful","jealous","nervous","sorrowful"]'::jsonb, 'grateful', 'grateful은 ''감사하는''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 4, 'intermediate', '"He felt ___ of his friend''s success." 빈칸에 들어갈 단어를 쓰시오. (질투하는)', 'short_answer', null, 'jealous', 'jealous는 ''질투하는''이라는 뜻입니다.'),
  ('english_vocab', 4, 'intermediate', '"She felt ___ after passing the test." 빈칸에 들어갈 단어를 쓰시오. (안도한)', 'short_answer', null, 'relieved', 'relieved는 ''안도한''이라는 뜻입니다.'),
  ('english_vocab', 4, 'advanced', '다음 중 부정적인 감정이 아닌 것은?', 'multiple_choice', '["grateful","furious","jealous","ashamed"]'::jsonb, 'grateful', 'grateful(감사하는)만 긍정적인 감정이고 나머지는 부정적인 감정입니다.'),
  ('english_vocab', 4, 'advanced', '''nervous''와 의미가 가장 가까운 단어는?', 'multiple_choice', '["anxious","relieved","grateful","eager"]'::jsonb, 'anxious', 'nervous와 anxious는 모두 ''불안한, 긴장한''이라는 뜻으로 비슷합니다.'),
  ('english_vocab', 4, 'advanced', '"After finishing the difficult exam, she felt deeply ___." 문맥상 가장 적절한 것은?', 'multiple_choice', '["relieved","furious","jealous","ashamed"]'::jsonb, 'relieved', 'relieved는 ''안도한''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 4, 'advanced', '''몹시 화난''이라는 뜻을 가진 단어는?', 'multiple_choice', '["furious","anxious","eager","grateful"]'::jsonb, 'furious', 'furious는 ''몹시 화난''이라는 뜻입니다.'),
  ('english_vocab', 4, 'advanced', '"He gave a ___ look after hearing the sad news." 문맥상 가장 적절한 것은?', 'multiple_choice', '["sorrowful","eager","curious","grateful"]'::jsonb, 'sorrowful', 'sorrowful은 ''슬픈''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 4, 'advanced', '다음 중 의미가 나머지 셋과 가장 다른 것은?', 'multiple_choice', '["eager","curious","ashamed","interested"]'::jsonb, 'ashamed', 'eager, curious, interested는 모두 적극적 관심을 나타내지만 ashamed는 ''부끄러운''이라는 다른 감정입니다.'),
  ('english_vocab', 4, 'advanced', '''슬픈, 애처로운''이라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'sorrowful', 'sorrowful은 ''슬픈, 애처로운''이라는 뜻입니다.'),
  ('english_vocab', 4, 'advanced', '''안도한''이라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'relieved', 'relieved는 ''안도한''이라는 뜻입니다.'),
  ('english_vocab', 5, 'beginner', '''acquaintance''의 뜻으로 알맞은 것은?', 'multiple_choice', '["아는 사람","동료","친척","이웃"]'::jsonb, '아는 사람', 'acquaintance는 ''아는 사람, 지인''이라는 뜻입니다.'),
  ('english_vocab', 5, 'beginner', '''colleague''의 뜻으로 알맞은 것은?', 'multiple_choice', '["동료","친척","이웃","낯선 사람"]'::jsonb, '동료', 'colleague는 ''동료''라는 뜻입니다.'),
  ('english_vocab', 5, 'beginner', '''neighbor''의 뜻으로 알맞은 것은?', 'multiple_choice', '["이웃","동료","배우자","형제자매"]'::jsonb, '이웃', 'neighbor는 ''이웃''이라는 뜻입니다.'),
  ('english_vocab', 5, 'beginner', '''relative''의 뜻으로 알맞은 것은?', 'multiple_choice', '["친척","이웃","동료","동반자"]'::jsonb, '친척', 'relative는 ''친척''이라는 뜻입니다.'),
  ('english_vocab', 5, 'beginner', '''sibling''의 뜻으로 알맞은 것은?', 'multiple_choice', '["형제자매","배우자","친척","십대"]'::jsonb, '형제자매', 'sibling은 ''형제자매''라는 뜻입니다.'),
  ('english_vocab', 5, 'beginner', '''stranger''의 뜻으로 알맞은 것은?', 'multiple_choice', '["낯선 사람","동료","이웃","친척"]'::jsonb, '낯선 사람', 'stranger는 ''낯선 사람''이라는 뜻입니다.'),
  ('english_vocab', 5, 'beginner', '''spouse''의 뜻을 한 단어로 쓰시오.', 'short_answer', null, '배우자', 'spouse는 ''배우자''라는 뜻입니다.'),
  ('english_vocab', 5, 'beginner', '''teenager''의 뜻을 한 단어로 쓰시오.', 'short_answer', null, '십대', 'teenager는 ''십대''라는 뜻입니다.'),
  ('english_vocab', 5, 'intermediate', '"He''s just an ___, not a close friend." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["acquaintance","colleague","sibling","spouse"]'::jsonb, 'acquaintance', 'acquaintance는 ''아는 사람''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 5, 'intermediate', '"My ___ helped me finish the project." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["colleague","stranger","neighbor","teenager"]'::jsonb, 'colleague', 'colleague는 ''동료''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 5, 'intermediate', '"My ___ is very kind and always says hello." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["neighbor","relative","spouse","stranger"]'::jsonb, 'neighbor', 'neighbor는 ''이웃''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 5, 'intermediate', '"I have several ___ living in Busan." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["relatives","colleagues","strangers","teenagers"]'::jsonb, 'relatives', 'relative는 ''친척''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 5, 'intermediate', '"Bring your ___ to the party this weekend." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["spouse","stranger","acquaintance","sibling"]'::jsonb, 'spouse', 'spouse는 ''배우자''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 5, 'intermediate', '"She was warned not to open the door for ___." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["strangers","siblings","relatives","colleagues"]'::jsonb, 'strangers', 'stranger는 ''낯선 사람''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 5, 'intermediate', '"I have two ___ who are older than me." 빈칸에 들어갈 단어를 쓰시오. (형제자매)', 'short_answer', null, 'siblings', 'sibling은 ''형제자매''라는 뜻입니다.'),
  ('english_vocab', 5, 'intermediate', '"Many ___ use social media every day." 빈칸에 들어갈 단어를 쓰시오. (십대)', 'short_answer', null, 'teenagers', 'teenager는 ''십대''라는 뜻입니다.'),
  ('english_vocab', 5, 'advanced', '다음 중 ''가족 구성원''을 가리키지 않는 것은?', 'multiple_choice', '["stranger","sibling","spouse","relative"]'::jsonb, 'stranger', 'sibling, spouse, relative는 모두 가족·친척 관계이지만 stranger는 ''낯선 사람''입니다.'),
  ('english_vocab', 5, 'advanced', '''acquaintance''와 ''colleague''의 차이로 가장 적절한 설명은?', 'multiple_choice', '["acquaintance는 단순히 아는 사이, colleague는 함께 일하는 사이","둘 다 완전히 같은 의미","acquaintance는 가족, colleague는 친구","차이가 없다"]'::jsonb, 'acquaintance는 단순히 아는 사이, colleague는 함께 일하는 사이', 'acquaintance는 단순히 알고 지내는 사람, colleague는 같이 일하는 동료를 뜻합니다.'),
  ('english_vocab', 5, 'advanced', '"a travel ___" 문맥상 가장 적절한 것은? (여행 동반자)', 'multiple_choice', '["companion","stranger","colleague","relative"]'::jsonb, 'companion', 'companion은 ''동반자, 동행''이라는 뜻입니다.'),
  ('english_vocab', 5, 'advanced', '''세대''라는 뜻을 가진 단어는?', 'multiple_choice', '["generation","companion","sibling","neighbor"]'::jsonb, 'generation', 'generation은 ''세대''라는 뜻입니다.'),
  ('english_vocab', 5, 'advanced', '"the younger ___" 문맥상 가장 적절한 것은? (젊은 세대)', 'multiple_choice', '["generation","neighbor","acquaintance","stranger"]'::jsonb, 'generation', 'generation은 ''세대''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 5, 'advanced', '다음 중 나이대를 가리키는 단어는?', 'multiple_choice', '["teenager","colleague","spouse","neighbor"]'::jsonb, 'teenager', 'teenager는 13~19세 사이의 나이대를 가리키는 단어입니다.'),
  ('english_vocab', 5, 'advanced', '''동반자, 동행''이라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'companion', 'companion은 ''동반자, 동행''이라는 뜻입니다.'),
  ('english_vocab', 5, 'advanced', '''세대''라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'generation', 'generation은 ''세대''라는 뜻입니다.');
