-- english_vocab question_bank seed — generated from c:/git_repository/5minuate_study/supabase/seed/english_vocab_day06-10.json
-- Supabase SQL 에디터에서 실행하세요 (question_bank 테이블이 먼저 생성되어 있어야 함)

insert into question_bank (curriculum_id, day_num, difficulty, question, type, options, answer, explanation) values
  ('english_vocab', 6, 'beginner', '''academic''의 뜻으로 알맞은 것은?', 'multiple_choice', '["학업의","과제","교육과정","강의"]'::jsonb, '학업의', 'academic은 ''학업의, 학문의''라는 뜻입니다.'),
  ('english_vocab', 6, 'beginner', '''assignment''의 뜻으로 알맞은 것은?', 'multiple_choice', '["과제","학업의","졸업하다","규율"]'::jsonb, '과제', 'assignment는 ''과제''라는 뜻입니다.'),
  ('english_vocab', 6, 'beginner', '''curriculum''의 뜻으로 알맞은 것은?', 'multiple_choice', '["교육과정","강의","장학금","과제"]'::jsonb, '교육과정', 'curriculum은 ''교육과정''이라는 뜻입니다.'),
  ('english_vocab', 6, 'beginner', '''discipline''의 뜻으로 알맞은 것은?', 'multiple_choice', '["규율, 훈육","교육과정","강의","학업의"]'::jsonb, '규율, 훈육', 'discipline은 ''규율, 훈육''이라는 뜻입니다.'),
  ('english_vocab', 6, 'beginner', '''graduate''의 뜻으로 알맞은 것은?', 'multiple_choice', '["졸업하다","과제","규율","강의"]'::jsonb, '졸업하다', 'graduate는 ''졸업하다''라는 뜻입니다.'),
  ('english_vocab', 6, 'beginner', '''lecture''의 뜻으로 알맞은 것은?', 'multiple_choice', '["강의","졸업하다","교육과정","장학금"]'::jsonb, '강의', 'lecture는 ''강의''라는 뜻입니다.'),
  ('english_vocab', 6, 'beginner', '''literacy''의 뜻을 쓰시오.', 'short_answer', null, '문해력', 'literacy는 ''문해력, 읽고 쓰는 능력''이라는 뜻입니다.'),
  ('english_vocab', 6, 'beginner', '''scholarship''의 뜻을 쓰시오.', 'short_answer', null, '장학금', 'scholarship은 ''장학금''이라는 뜻입니다.'),
  ('english_vocab', 6, 'intermediate', '"Her ___ performance improved a lot this year." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["academic","elementary","literacy","discipline"]'::jsonb, 'academic', 'academic performance는 ''학업 성취도''라는 뜻의 표현입니다.'),
  ('english_vocab', 6, 'intermediate', '"Submit your ___ by Friday." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["assignment","scholarship","semester","lecture"]'::jsonb, 'assignment', 'assignment는 ''과제''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 6, 'intermediate', '"The school introduced a new ___ this year." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["curriculum","discipline","literacy","semester"]'::jsonb, 'curriculum', 'curriculum은 ''교육과정''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 6, 'intermediate', '"Self-___ is important for online learning." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["discipline","literacy","scholarship","assignment"]'::jsonb, 'discipline', 'self-discipline은 ''자기 규율, 자기 절제''라는 뜻의 표현입니다.'),
  ('english_vocab', 6, 'intermediate', '"She will ___ from university next year." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["graduate","discipline","assignment","semester"]'::jsonb, 'graduate', 'graduate from은 ''~을 졸업하다''라는 뜻입니다.'),
  ('english_vocab', 6, 'intermediate', '"I attended an interesting ___ on economics." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["lecture","curriculum","assignment","scholarship"]'::jsonb, 'lecture', 'lecture는 ''강의''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 6, 'intermediate', '"Digital ___ is essential in modern society." 빈칸에 들어갈 단어를 쓰시오.', 'short_answer', null, 'literacy', 'digital literacy는 ''디지털 문해력''이라는 뜻의 표현입니다.'),
  ('english_vocab', 6, 'intermediate', '"He received a ___ to study abroad." 빈칸에 들어갈 단어를 쓰시오. (장학금)', 'short_answer', null, 'scholarship', 'scholarship은 ''장학금''이라는 뜻입니다.'),
  ('english_vocab', 6, 'advanced', '다음 중 의미가 나머지 셋과 가장 다른 것은?', 'multiple_choice', '["academic","elementary","basic","fundamental"]'::jsonb, 'academic', 'elementary, basic, fundamental은 모두 ''기초적인''이라는 뜻이지만 academic은 ''학업의, 학문의''라는 다른 의미입니다.'),
  ('english_vocab', 6, 'advanced', '''semester''와 의미가 가장 가까운 단어는?', 'multiple_choice', '["term","lecture","curriculum","discipline"]'::jsonb, 'term', 'semester와 term은 모두 ''학기''를 뜻합니다.'),
  ('english_vocab', 6, 'advanced', '"The professor''s ___ was rescheduled to next week." 문맥상 가장 적절한 것은?', 'multiple_choice', '["lecture","discipline","literacy","curriculum"]'::jsonb, 'lecture', 'lecture는 ''강의''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 6, 'advanced', '''규율, 훈육''이라는 뜻을 가진 단어는?', 'multiple_choice', '["discipline","assignment","scholarship","semester"]'::jsonb, 'discipline', 'discipline은 ''규율, 훈육''이라는 뜻입니다.'),
  ('english_vocab', 6, 'advanced', '"He was awarded a full ___ covering tuition and housing." 문맥상 가장 적절한 것은?', 'multiple_choice', '["scholarship","assignment","lecture","curriculum"]'::jsonb, 'scholarship', 'scholarship은 ''장학금''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 6, 'advanced', '''교외의, 초등의''라는 뜻으로 ''school''과 함께 쓰이는 단어는?', 'multiple_choice', '["elementary","academic","graduate","literacy"]'::jsonb, 'elementary', 'elementary school은 ''초등학교''라는 뜻의 표현입니다.'),
  ('english_vocab', 6, 'advanced', '''교육과정''이라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'curriculum', 'curriculum은 ''교육과정''이라는 뜻입니다.'),
  ('english_vocab', 6, 'advanced', '''학기''라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'semester', 'semester는 ''학기''라는 뜻입니다.'),
  ('english_vocab', 7, 'beginner', '''constantly''의 뜻으로 알맞은 것은?', 'multiple_choice', '["끊임없이","결국","자주","가끔"]'::jsonb, '끊임없이', 'constantly는 ''끊임없이''라는 뜻입니다.'),
  ('english_vocab', 7, 'beginner', '''frequently''의 뜻으로 알맞은 것은?', 'multiple_choice', '["자주","점차","즉시","드물게"]'::jsonb, '자주', 'frequently는 ''자주''라는 뜻입니다.'),
  ('english_vocab', 7, 'beginner', '''gradually''의 뜻으로 알맞은 것은?', 'multiple_choice', '["점차","즉시","끊임없이","가끔"]'::jsonb, '점차', 'gradually는 ''점차, 점진적으로''라는 뜻입니다.'),
  ('english_vocab', 7, 'beginner', '''immediately''의 뜻으로 알맞은 것은?', 'multiple_choice', '["즉시","결국","자주","일시적으로"]'::jsonb, '즉시', 'immediately는 ''즉시''라는 뜻입니다.'),
  ('english_vocab', 7, 'beginner', '''occasionally''의 뜻으로 알맞은 것은?', 'multiple_choice', '["가끔","드물게","영구적으로","이전에"]'::jsonb, '가끔', 'occasionally는 ''가끔''이라는 뜻입니다.'),
  ('english_vocab', 7, 'beginner', '''rarely''의 뜻으로 알맞은 것은?', 'multiple_choice', '["드물게","가끔","점차","결국"]'::jsonb, '드물게', 'rarely는 ''드물게, 좀처럼 ~않다''라는 뜻입니다.'),
  ('english_vocab', 7, 'beginner', '''previously''의 뜻을 쓰시오.', 'short_answer', null, '이전에', 'previously는 ''이전에''라는 뜻입니다.'),
  ('english_vocab', 7, 'beginner', '''temporarily''의 뜻을 쓰시오.', 'short_answer', null, '일시적으로', 'temporarily는 ''일시적으로''라는 뜻입니다.'),
  ('english_vocab', 7, 'intermediate', '"He''s ___ checking his phone during class." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["constantly","occasionally","rarely","eventually"]'::jsonb, 'constantly', 'constantly는 ''끊임없이''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 7, 'intermediate', '"She ___ succeeded after years of effort." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["eventually","immediately","previously","temporarily"]'::jsonb, 'eventually', 'eventually는 ''결국''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 7, 'intermediate', '"They ___ visit their grandparents on weekends." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["frequently","rarely","permanently","gradually"]'::jsonb, 'frequently', 'frequently는 ''자주''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 7, 'intermediate', '"The weather is ___ improving this week." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["gradually","immediately","constantly","occasionally"]'::jsonb, 'gradually', 'gradually는 ''점차''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 7, 'intermediate', '"Please call me ___ if anything happens." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["immediately","eventually","previously","rarely"]'::jsonb, 'immediately', 'immediately는 ''즉시''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 7, 'intermediate', '"I ___ eat fast food, maybe once a month." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["occasionally","constantly","frequently","permanently"]'::jsonb, 'occasionally', 'occasionally는 ''가끔''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 7, 'intermediate', '"The shop closed ___." 빈칸에 들어갈 단어를 쓰시오. (영구적으로)', 'short_answer', null, 'permanently', 'permanently는 ''영구적으로''라는 뜻입니다.'),
  ('english_vocab', 7, 'intermediate', '"As ___ mentioned in the report, sales have declined." 빈칸에 들어갈 단어를 쓰시오. (이전에)', 'short_answer', null, 'previously', 'previously는 ''이전에''라는 뜻입니다.'),
  ('english_vocab', 7, 'advanced', '다음 중 의미가 나머지 셋과 가장 다른 것은?', 'multiple_choice', '["frequently","rarely","seldom","hardly"]'::jsonb, 'frequently', 'rarely, seldom, hardly는 모두 ''거의 ~않다''라는 뜻이지만 frequently는 ''자주''라는 반대 의미입니다.'),
  ('english_vocab', 7, 'advanced', '''temporarily''와 의미가 가장 가까운 단어는?', 'multiple_choice', '["briefly","permanently","constantly","gradually"]'::jsonb, 'briefly', 'temporarily와 briefly는 모두 ''잠시, 일시적으로''라는 뜻입니다.'),
  ('english_vocab', 7, 'advanced', '"The road is ___ closed for repairs." 문맥상 가장 적절한 것은?', 'multiple_choice', '["temporarily","permanently","rarely","eventually"]'::jsonb, 'temporarily', 'temporarily는 ''일시적으로''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 7, 'advanced', '''결국''이라는 뜻을 가진 단어는?', 'multiple_choice', '["eventually","immediately","previously","occasionally"]'::jsonb, 'eventually', 'eventually는 ''결국''이라는 뜻입니다.'),
  ('english_vocab', 7, 'advanced', '"The company ___ went bankrupt after years of losses." 문맥상 가장 적절한 것은?', 'multiple_choice', '["eventually","temporarily","rarely","constantly"]'::jsonb, 'eventually', 'eventually는 ''결국''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 7, 'advanced', '"He ___ gets angry, even under pressure." 문맥상 가장 적절한 것은?', 'multiple_choice', '["rarely","constantly","frequently","gradually"]'::jsonb, 'rarely', 'rarely는 ''좀처럼 ~않다''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 7, 'advanced', '''즉시''라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'immediately', 'immediately는 ''즉시''라는 뜻입니다.'),
  ('english_vocab', 7, 'advanced', '''점차, 점진적으로''라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'gradually', 'gradually는 ''점차, 점진적으로''라는 뜻입니다.'),
  ('english_vocab', 8, 'beginner', '''destination''의 뜻으로 알맞은 것은?', 'multiple_choice', '["목적지","경로","지역","차량"]'::jsonb, '목적지', 'destination은 ''목적지''라는 뜻입니다.'),
  ('english_vocab', 8, 'beginner', '''journey''의 뜻으로 알맞은 것은?', 'multiple_choice', '["여행, 여정","목적지","경계","영토"]'::jsonb, '여행, 여정', 'journey는 ''여행, 여정''이라는 뜻입니다.'),
  ('english_vocab', 8, 'beginner', '''nearby''의 뜻으로 알맞은 것은?', 'multiple_choice', '["근처의","교외의","지역의","경로의"]'::jsonb, '근처의', 'nearby는 ''근처의, 근처에''라는 뜻입니다.'),
  ('english_vocab', 8, 'beginner', '''region''의 뜻으로 알맞은 것은?', 'multiple_choice', '["지역","경로","차량","목적지"]'::jsonb, '지역', 'region은 ''지역''이라는 뜻입니다.'),
  ('english_vocab', 8, 'beginner', '''route''의 뜻으로 알맞은 것은?', 'multiple_choice', '["경로","여정","지역","경계"]'::jsonb, '경로', 'route는 ''경로''라는 뜻입니다.'),
  ('english_vocab', 8, 'beginner', '''vehicle''의 뜻으로 알맞은 것은?', 'multiple_choice', '["차량","여정","목적지","경로"]'::jsonb, '차량', 'vehicle은 ''차량''이라는 뜻입니다.'),
  ('english_vocab', 8, 'beginner', '''suburb''의 뜻을 쓰시오.', 'short_answer', null, '교외', 'suburb는 ''교외''라는 뜻입니다.'),
  ('english_vocab', 8, 'beginner', '''territory''의 뜻을 쓰시오.', 'short_answer', null, '영토', 'territory는 ''영토''라는 뜻입니다.'),
  ('english_vocab', 8, 'intermediate', '"Our ___ is Seoul." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["destination","route","region","territory"]'::jsonb, 'destination', 'destination은 ''목적지''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 8, 'intermediate', '"They moved to a quiet ___ outside the city." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["suburb","region","territory","boundary"]'::jsonb, 'suburb', 'suburb는 ''교외''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 8, 'intermediate', '"We took the shortest ___ to the airport." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["route","journey","destination","boundary"]'::jsonb, 'route', 'route는 ''경로''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 8, 'intermediate', '"An electric ___ is more eco-friendly." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["vehicle","journey","route","region"]'::jsonb, 'vehicle', 'vehicle은 ''차량''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 8, 'intermediate', '"There''s a ___ restaurant we can walk to." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["nearby","region","route","territory"]'::jsonb, 'nearby', 'nearby는 ''근처의''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 8, 'intermediate', '"Wild geese ___ south when winter comes." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["migrate","journey","route","nearby"]'::jsonb, 'migrate', 'migrate는 ''이주하다''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 8, 'intermediate', '"The ___ between the two countries is heavily guarded." 빈칸에 들어갈 단어를 쓰시오. (경계)', 'short_answer', null, 'boundary', 'boundary는 ''경계''라는 뜻입니다.'),
  ('english_vocab', 8, 'intermediate', '"It was a long ___ across the mountains." 빈칸에 들어갈 단어를 쓰시오. (여행, 여정)', 'short_answer', null, 'journey', 'journey는 ''여행, 여정''이라는 뜻입니다.'),
  ('english_vocab', 8, 'advanced', '다음 중 의미가 나머지 셋과 가장 다른 것은?', 'multiple_choice', '["vehicle","region","territory","area"]'::jsonb, 'vehicle', 'region, territory, area는 모두 ''지역, 영역''이라는 뜻이지만 vehicle은 ''차량''이라는 다른 의미입니다.'),
  ('english_vocab', 8, 'advanced', '''journey''와 의미가 가장 가까운 단어는?', 'multiple_choice', '["trip","boundary","route","suburb"]'::jsonb, 'trip', 'journey와 trip은 모두 ''여행''이라는 뜻입니다.'),
  ('english_vocab', 8, 'advanced', '"Wild geese ___ to warmer regions every winter." 문맥상 가장 적절한 것은?', 'multiple_choice', '["migrate","journey","route","nearby"]'::jsonb, 'migrate', 'migrate는 ''이주하다''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 8, 'advanced', '''경계''라는 뜻을 가진 단어는?', 'multiple_choice', '["boundary","territory","region","route"]'::jsonb, 'boundary', 'boundary는 ''경계''라는 뜻입니다.'),
  ('english_vocab', 8, 'advanced', '"This area belongs to the tiger''s ___." 문맥상 가장 적절한 것은?', 'multiple_choice', '["territory","boundary","region","suburb"]'::jsonb, 'territory', 'territory는 ''영토, 세력권''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 8, 'advanced', '''교외''라는 뜻을 가진 단어는?', 'multiple_choice', '["suburb","region","territory","boundary"]'::jsonb, 'suburb', 'suburb는 ''교외''라는 뜻입니다.'),
  ('english_vocab', 8, 'advanced', '''목적지''라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'destination', 'destination은 ''목적지''라는 뜻입니다.'),
  ('english_vocab', 8, 'advanced', '''경로''라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'route', 'route는 ''경로''라는 뜻입니다.'),
  ('english_vocab', 9, 'beginner', '''climate''의 뜻으로 알맞은 것은?', 'multiple_choice', '["기후","천둥","온도","야생동물"]'::jsonb, '기후', 'climate는 ''기후''라는 뜻입니다.'),
  ('english_vocab', 9, 'beginner', '''humid''의 뜻으로 알맞은 것은?', 'multiple_choice', '["습한","건조한","따뜻한","차가운"]'::jsonb, '습한', 'humid는 ''습한''이라는 뜻입니다.'),
  ('english_vocab', 9, 'beginner', '''rainfall''의 뜻으로 알맞은 것은?', 'multiple_choice', '["강우량","기후","습기","천둥"]'::jsonb, '강우량', 'rainfall은 ''강우량''이라는 뜻입니다.'),
  ('english_vocab', 9, 'beginner', '''temperature''의 뜻으로 알맞은 것은?', 'multiple_choice', '["온도, 기온","기후","습기","강우량"]'::jsonb, '온도, 기온', 'temperature는 ''온도, 기온''이라는 뜻입니다.'),
  ('english_vocab', 9, 'beginner', '''thunder''의 뜻으로 알맞은 것은?', 'multiple_choice', '["천둥","가뭄","습기","초목"]'::jsonb, '천둥', 'thunder는 ''천둥''이라는 뜻입니다.'),
  ('english_vocab', 9, 'beginner', '''wildlife''의 뜻으로 알맞은 것은?', 'multiple_choice', '["야생동물","초목","대기","가뭄"]'::jsonb, '야생동물', 'wildlife는 ''야생동물''이라는 뜻입니다.'),
  ('english_vocab', 9, 'beginner', '''moisture''의 뜻을 쓰시오.', 'short_answer', null, '습기', 'moisture는 ''습기, 수분''이라는 뜻입니다.'),
  ('english_vocab', 9, 'beginner', '''vegetation''의 뜻을 쓰시오.', 'short_answer', null, '초목', 'vegetation은 ''초목, 식생''이라는 뜻입니다.'),
  ('english_vocab', 9, 'intermediate', '"This region has a dry ___ with very little rain." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["climate","atmosphere","rainfall","temperature"]'::jsonb, 'climate', 'climate는 ''기후''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 9, 'intermediate', '"It''s hot and ___ today; the air feels heavy." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["humid","dry","cold","mild"]'::jsonb, 'humid', 'humid는 ''습한''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 9, 'intermediate', '"We heard ___ rumbling in the distance before the storm." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["thunder","rainfall","drought","moisture"]'::jsonb, 'thunder', 'thunder는 ''천둥''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 9, 'intermediate', '"The ___ rose to 35 degrees this afternoon." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["temperature","climate","rainfall","atmosphere"]'::jsonb, 'temperature', 'temperature는 ''온도, 기온''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 9, 'intermediate', '"Farmers are worried about the lack of rain and the growing ___." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["drought","moisture","rainfall","climate"]'::jsonb, 'drought', 'drought는 ''가뭄''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 9, 'intermediate', '"The festival''s ___ was lively and cheerful." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["atmosphere","climate","temperature","thunder"]'::jsonb, 'atmosphere', '여기서 atmosphere는 ''분위기''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 9, 'intermediate', '"The soil needs more ___ to grow crops." 빈칸에 들어갈 단어를 쓰시오. (습기, 수분)', 'short_answer', null, 'moisture', 'moisture는 ''습기, 수분''이라는 뜻입니다.'),
  ('english_vocab', 9, 'intermediate', '"Heavy ___ caused flooding in the city." 빈칸에 들어갈 단어를 쓰시오. (강우량)', 'short_answer', null, 'rainfall', 'rainfall은 ''강우량''이라는 뜻입니다.'),
  ('english_vocab', 9, 'advanced', '다음 중 의미가 나머지 셋과 가장 다른 것은?', 'multiple_choice', '["vegetation","climate","temperature","rainfall"]'::jsonb, 'vegetation', 'climate, temperature, rainfall은 모두 날씨를 측정하는 요소이지만 vegetation은 ''초목, 식물''을 가리키는 다른 의미입니다.'),
  ('english_vocab', 9, 'advanced', '''atmosphere''가 ''분위기''라는 뜻일 때 의미가 가장 가까운 단어는?', 'multiple_choice', '["mood","climate","drought","vegetation"]'::jsonb, 'mood', '이때 atmosphere와 mood는 모두 ''분위기''라는 뜻입니다.'),
  ('english_vocab', 9, 'advanced', '"The prolonged ___ destroyed most of the crops." 문맥상 가장 적절한 것은?', 'multiple_choice', '["drought","rainfall","moisture","thunder"]'::jsonb, 'drought', 'drought는 ''가뭄''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 9, 'advanced', '''초목, 식생''이라는 뜻을 가진 단어는?', 'multiple_choice', '["vegetation","wildlife","climate","atmosphere"]'::jsonb, 'vegetation', 'vegetation은 ''초목, 식생''이라는 뜻입니다.'),
  ('english_vocab', 9, 'advanced', '"Conservation groups work to protect local ___." 문맥상 가장 적절한 것은?', 'multiple_choice', '["wildlife","climate","drought","atmosphere"]'::jsonb, 'wildlife', 'wildlife는 ''야생동물''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 9, 'advanced', '"the Earth''s ___" 빈칸에 가장 적절한 것은? (대기)', 'multiple_choice', '["atmosphere","climate","temperature","vegetation"]'::jsonb, 'atmosphere', 'atmosphere는 ''대기''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 9, 'advanced', '''기후''라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'climate', 'climate는 ''기후''라는 뜻입니다.'),
  ('english_vocab', 9, 'advanced', '''온도, 기온''이라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'temperature', 'temperature는 ''온도, 기온''이라는 뜻입니다.'),
  ('english_vocab', 10, 'beginner', '''creature''의 뜻으로 알맞은 것은?', 'multiple_choice', '["생물","서식지","영양소","포식자"]'::jsonb, '생물', 'creature는 ''생물''이라는 뜻입니다.'),
  ('english_vocab', 10, 'beginner', '''habitat''의 뜻으로 알맞은 것은?', 'multiple_choice', '["서식지","생물","종","포식자"]'::jsonb, '서식지', 'habitat은 ''서식지''라는 뜻입니다.'),
  ('english_vocab', 10, 'beginner', '''insect''의 뜻으로 알맞은 것은?', 'multiple_choice', '["곤충","포유류","포식자","유기체"]'::jsonb, '곤충', 'insect는 ''곤충''이라는 뜻입니다.'),
  ('english_vocab', 10, 'beginner', '''mammal''의 뜻으로 알맞은 것은?', 'multiple_choice', '["포유류","곤충","포식자","종"]'::jsonb, '포유류', 'mammal은 ''포유류''라는 뜻입니다.'),
  ('english_vocab', 10, 'beginner', '''predator''의 뜻으로 알맞은 것은?', 'multiple_choice', '["포식자","생물","서식지","포유류"]'::jsonb, '포식자', 'predator는 ''포식자''라는 뜻입니다.'),
  ('english_vocab', 10, 'beginner', '''species''의 뜻으로 알맞은 것은?', 'multiple_choice', '["종(種)","서식지","영양소","유기체"]'::jsonb, '종(種)', 'species는 ''종(種)''이라는 뜻입니다.'),
  ('english_vocab', 10, 'beginner', '''nutrient''의 뜻을 쓰시오.', 'short_answer', null, '영양소', 'nutrient는 ''영양소''라는 뜻입니다.'),
  ('english_vocab', 10, 'beginner', '''organism''의 뜻을 쓰시오.', 'short_answer', null, '유기체', 'organism은 ''유기체''라는 뜻입니다.'),
  ('english_vocab', 10, 'intermediate', '"Tigers are a natural ___ of deer." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["predator","mammal","species","creature"]'::jsonb, 'predator', 'predator는 ''포식자''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 10, 'intermediate', '"A bee is a common ___ found in gardens." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["insect","mammal","creature","organism"]'::jsonb, 'insect', 'insect는 ''곤충''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 10, 'intermediate', '"A whale is a large ocean-dwelling ___." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["mammal","insect","predator","species"]'::jsonb, 'mammal', 'mammal은 ''포유류''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 10, 'intermediate', '"Tigers need a large ___ to hunt and survive." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["habitat","species","nutrient","organism"]'::jsonb, 'habitat', 'habitat은 ''서식지''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 10, 'intermediate', '"A plant absorbs ___s from the soil to grow." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["nutrient","habitat","organism","species"]'::jsonb, 'nutrient', 'nutrient는 ''영양소''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 10, 'intermediate', '"Every living ___, from bacteria to humans, needs energy." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["organism","creature","species","predator"]'::jsonb, 'organism', 'organism은 ''유기체''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 10, 'intermediate', '"Pandas are an ___ species." 빈칸에 들어갈 단어를 쓰시오. (멸종 위기의)', 'short_answer', null, 'endangered', 'endangered는 ''멸종 위기의''라는 뜻입니다.'),
  ('english_vocab', 10, 'intermediate', '"Farmers ___ cattle for milk and meat." 빈칸에 들어갈 단어를 쓰시오. (사육하다)', 'short_answer', null, 'breed', 'breed는 동사로 ''사육하다, 기르다''라는 뜻입니다.'),
  ('english_vocab', 10, 'advanced', '다음 중 의미가 나머지 셋과 가장 다른 것은?', 'multiple_choice', '["habitat","creature","organism","species"]'::jsonb, 'habitat', 'creature, organism, species는 모두 생물 그 자체를 가리키지만 habitat은 그 생물이 사는 ''장소''를 가리키는 다른 의미입니다.'),
  ('english_vocab', 10, 'advanced', '''creature''와 의미가 가장 가까운 단어는?', 'multiple_choice', '["being","predator","habitat","breed"]'::jsonb, 'being', 'creature와 being은 모두 ''생물, 존재''라는 뜻입니다.'),
  ('english_vocab', 10, 'advanced', '"Deforestation is destroying the ___ of many species." 문맥상 가장 적절한 것은?', 'multiple_choice', '["habitat","breed","nutrient","predator"]'::jsonb, 'habitat', 'habitat은 ''서식지''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 10, 'advanced', '''멸종 위기의''라는 뜻을 가진 단어는?', 'multiple_choice', '["endangered","predator","mammal","organism"]'::jsonb, 'endangered', 'endangered는 ''멸종 위기의''라는 뜻입니다.'),
  ('english_vocab', 10, 'advanced', '"Lions are apex ___s with no natural enemies." 문맥상 가장 적절한 것은?', 'multiple_choice', '["predator","mammal","species","insect"]'::jsonb, 'predator', 'predator는 ''포식자''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 10, 'advanced', '"a rare ___ of dog" 빈칸에 가장 적절한 것은?', 'multiple_choice', '["breed","species","organism","creature"]'::jsonb, 'breed', '이때 breed는 명사로 ''품종''이라는 뜻입니다.'),
  ('english_vocab', 10, 'advanced', '''서식지''라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'habitat', 'habitat은 ''서식지''라는 뜻입니다.'),
  ('english_vocab', 10, 'advanced', '''종(種)''이라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'species', 'species는 ''종(種)''이라는 뜻입니다.');
