-- english_vocab question_bank seed — generated from c:/git_repository/5minuate_study/supabase/seed/english_vocab_day11-15.json
-- Supabase SQL 에디터에서 실행하세요 (question_bank 테이블이 먼저 생성되어 있어야 함)

insert into question_bank (curriculum_id, day_num, difficulty, question, type, options, answer, explanation) values
  ('english_vocab', 11, 'beginner', '''community''의 뜻으로 알맞은 것은?', 'multiple_choice', '["공동체","문화","관습","기관"]'::jsonb, '공동체', 'community는 ''공동체''라는 뜻입니다.'),
  ('english_vocab', 11, 'beginner', '''culture''의 뜻으로 알맞은 것은?', 'multiple_choice', '["문화","공동체","규범","전통"]'::jsonb, '문화', 'culture는 ''문화''라는 뜻입니다.'),
  ('english_vocab', 11, 'beginner', '''custom''의 뜻으로 알맞은 것은?', 'multiple_choice', '["관습","전통","규범","복지"]'::jsonb, '관습', 'custom은 ''관습''이라는 뜻입니다.'),
  ('english_vocab', 11, 'beginner', '''diversity''의 뜻으로 알맞은 것은?', 'multiple_choice', '["다양성","소수 집단","복지","규범"]'::jsonb, '다양성', 'diversity는 ''다양성''이라는 뜻입니다.'),
  ('english_vocab', 11, 'beginner', '''institution''의 뜻으로 알맞은 것은?', 'multiple_choice', '["기관","공동체","전통","관습"]'::jsonb, '기관', 'institution은 ''기관''이라는 뜻입니다.'),
  ('english_vocab', 11, 'beginner', '''tradition''의 뜻으로 알맞은 것은?', 'multiple_choice', '["전통","관습","규범","문화"]'::jsonb, '전통', 'tradition은 ''전통''이라는 뜻입니다.'),
  ('english_vocab', 11, 'beginner', '''minority''의 뜻을 쓰시오.', 'short_answer', null, '소수 집단', 'minority는 ''소수 집단''이라는 뜻입니다.'),
  ('english_vocab', 11, 'beginner', '''norm''의 뜻을 쓰시오.', 'short_answer', null, '규범', 'norm은 ''규범''이라는 뜻입니다.'),
  ('english_vocab', 11, 'intermediate', '"They live in a close-knit ___." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["community","culture","institution","tradition"]'::jsonb, 'community', 'community는 ''공동체''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 11, 'intermediate', '"Respecting other people''s ___ is important when traveling." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["culture","custom","tradition","institution"]'::jsonb, 'culture', 'culture는 ''문화''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 11, 'intermediate', '"It''s a local ___ to remove shoes before entering a house." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["custom","tradition","norm","culture"]'::jsonb, 'custom', 'custom은 ''관습''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 11, 'intermediate', '"The company values ___ among its employees." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["diversity","community","welfare","minority"]'::jsonb, 'diversity', 'diversity는 ''다양성''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 11, 'intermediate', '"The university is a respected educational ___." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["institution","tradition","community","norm"]'::jsonb, 'institution', 'institution은 ''기관''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 11, 'intermediate', '"Passing down family recipes is a long-standing ___." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["tradition","custom","culture","norm"]'::jsonb, 'tradition', 'tradition은 ''전통''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 11, 'intermediate', '"The government increased spending on social ___." 빈칸에 들어갈 단어를 쓰시오. (복지)', 'short_answer', null, 'welfare', 'welfare는 ''복지''라는 뜻입니다.'),
  ('english_vocab', 11, 'intermediate', '"The ___ groups in this region speak different languages." 빈칸에 들어갈 단어를 쓰시오. (민족의)', 'short_answer', null, 'ethnic', 'ethnic은 ''민족의''라는 뜻입니다.'),
  ('english_vocab', 11, 'advanced', '다음 중 의미가 나머지 셋과 가장 다른 것은?', 'multiple_choice', '["minority","custom","tradition","norm"]'::jsonb, 'minority', 'custom, tradition, norm은 모두 공유된 사회적 관행을 뜻하지만 minority는 ''소수 집단''을 가리키는 다른 의미입니다.'),
  ('english_vocab', 11, 'advanced', '''norm''과 의미가 가장 가까운 단어는?', 'multiple_choice', '["standard","custom","welfare","institution"]'::jsonb, 'standard', 'norm과 standard는 모두 ''기준, 규범''이라는 뜻입니다.'),
  ('english_vocab', 11, 'advanced', '"___ groups deserve equal protection under the law." 문맥상 가장 적절한 것은?', 'multiple_choice', '["minority","ethnic","institution","welfare"]'::jsonb, 'minority', 'minority는 ''소수 집단''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 11, 'advanced', '''다양성''이라는 뜻을 가진 단어는?', 'multiple_choice', '["diversity","community","custom","norm"]'::jsonb, 'diversity', 'diversity는 ''다양성''이라는 뜻입니다.'),
  ('english_vocab', 11, 'advanced', '"The organization provides ___ services for low-income families." 문맥상 가장 적절한 것은?', 'multiple_choice', '["welfare","custom","tradition","institution"]'::jsonb, 'welfare', 'welfare는 ''복지''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 11, 'advanced', '"Kurds are an ___ minority in several Middle Eastern countries." 문맥상 가장 적절한 것은?', 'multiple_choice', '["ethnic","cultural","religious","social"]'::jsonb, 'ethnic', 'ethnic minority는 ''민족적 소수 집단''이라는 뜻의 표현입니다.'),
  ('english_vocab', 11, 'advanced', '''전통''이라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'tradition', 'tradition은 ''전통''이라는 뜻입니다.'),
  ('english_vocab', 11, 'advanced', '''규범''이라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'norm', 'norm은 ''규범''이라는 뜻입니다.'),
  ('english_vocab', 12, 'beginner', '''budget''의 뜻으로 알맞은 것은?', 'multiple_choice', '["예산","소득","이익","비용"]'::jsonb, '예산', 'budget은 ''예산''이라는 뜻입니다.'),
  ('english_vocab', 12, 'beginner', '''consumer''의 뜻으로 알맞은 것은?', 'multiple_choice', '["소비자","화폐","경제","투자"]'::jsonb, '소비자', 'consumer는 ''소비자''라는 뜻입니다.'),
  ('english_vocab', 12, 'beginner', '''currency''의 뜻으로 알맞은 것은?', 'multiple_choice', '["화폐","소비자","예산","수익"]'::jsonb, '화폐', 'currency는 ''화폐''라는 뜻입니다.'),
  ('english_vocab', 12, 'beginner', '''economy''의 뜻으로 알맞은 것은?', 'multiple_choice', '["경제","화폐","예산","이익"]'::jsonb, '경제', 'economy는 ''경제''라는 뜻입니다.'),
  ('english_vocab', 12, 'beginner', '''income''의 뜻으로 알맞은 것은?', 'multiple_choice', '["소득","비용","이익","투자"]'::jsonb, '소득', 'income은 ''소득''이라는 뜻입니다.'),
  ('english_vocab', 12, 'beginner', '''profit''의 뜻으로 알맞은 것은?', 'multiple_choice', '["이익","소득","비용","예산"]'::jsonb, '이익', 'profit은 ''이익''이라는 뜻입니다.'),
  ('english_vocab', 12, 'beginner', '''expense''의 뜻을 쓰시오.', 'short_answer', null, '비용', 'expense는 ''비용''이라는 뜻입니다.'),
  ('english_vocab', 12, 'beginner', '''investment''의 뜻을 쓰시오.', 'short_answer', null, '투자', 'investment는 ''투자''라는 뜻입니다.'),
  ('english_vocab', 12, 'intermediate', '"We need to stick to our ___ this month." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["budget","expense","income","profit"]'::jsonb, 'budget', 'budget은 ''예산''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 12, 'intermediate', '"___ rights protect people who buy goods and services." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["Consumer","Currency","Economy","Income"]'::jsonb, 'Consumer', 'consumer는 ''소비자''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 12, 'intermediate', '"The exchange rate between the two ___s changed overnight." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["currency","economy","revenue","expense"]'::jsonb, 'currency', 'currency는 ''화폐''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 12, 'intermediate', '"The country''s ___ has grown steadily over the past decade." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["economy","budget","currency","profit"]'::jsonb, 'economy', 'economy는 ''경제''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 12, 'intermediate', '"Her monthly ___ covers rent and groceries." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["income","expense","profit","revenue"]'::jsonb, 'income', 'income은 ''소득''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 12, 'intermediate', '"The company made a large ___ this quarter." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["profit","expense","budget","income"]'::jsonb, 'profit', 'profit은 ''이익''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 12, 'intermediate', '"Rent is our biggest monthly ___." 빈칸에 들어갈 단어를 쓰시오. (비용)', 'short_answer', null, 'expense', 'expense는 ''비용''이라는 뜻입니다.'),
  ('english_vocab', 12, 'intermediate', '"They made a wise ___ in real estate." 빈칸에 들어갈 단어를 쓰시오. (투자)', 'short_answer', null, 'investment', 'investment는 ''투자''라는 뜻입니다.'),
  ('english_vocab', 12, 'advanced', '다음 중 의미가 나머지 셋과 가장 다른 것은?', 'multiple_choice', '["expense","income","revenue","profit"]'::jsonb, 'expense', 'income, revenue, profit은 모두 들어오는 돈을 뜻하지만 expense는 나가는 ''비용''을 뜻하는 다른 의미입니다.'),
  ('english_vocab', 12, 'advanced', '''commerce''와 의미가 가장 가까운 단어는?', 'multiple_choice', '["trade","budget","currency","income"]'::jsonb, 'trade', 'commerce와 trade는 모두 ''상업, 무역''이라는 뜻입니다.'),
  ('english_vocab', 12, 'advanced', '"The company''s annual ___ exceeded expectations." 문맥상 가장 적절한 것은?', 'multiple_choice', '["revenue","expense","budget","currency"]'::jsonb, 'revenue', 'revenue는 ''수익, 세입''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 12, 'advanced', '''상업''이라는 뜻을 가진 단어는?', 'multiple_choice', '["commerce","economy","consumer","investment"]'::jsonb, 'commerce', 'commerce는 ''상업''이라는 뜻입니다.'),
  ('english_vocab', 12, 'advanced', '"A wise ___ can grow your wealth over time." 문맥상 가장 적절한 것은?', 'multiple_choice', '["investment","expense","budget","revenue"]'::jsonb, 'investment', 'investment는 ''투자''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 12, 'advanced', '"Online ___ has grown rapidly in recent years." 빈칸에 가장 적절한 것은?', 'multiple_choice', '["commerce","currency","income","profit"]'::jsonb, 'commerce', 'commerce는 ''상업''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 12, 'advanced', '''화폐''라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'currency', 'currency는 ''화폐''라는 뜻입니다.'),
  ('english_vocab', 12, 'advanced', '''수익, 세입''이라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'revenue', 'revenue는 ''수익, 세입''이라는 뜻입니다.'),
  ('english_vocab', 13, 'beginner', '''device''의 뜻으로 알맞은 것은?', 'multiple_choice', '["기기","혁신","발명","이론"]'::jsonb, '기기', 'device는 ''기기''라는 뜻입니다.'),
  ('english_vocab', 13, 'beginner', '''innovation''의 뜻으로 알맞은 것은?', 'multiple_choice', '["혁신","발명","기기","실험실"]'::jsonb, '혁신', 'innovation은 ''혁신''이라는 뜻입니다.'),
  ('english_vocab', 13, 'beginner', '''invention''의 뜻으로 알맞은 것은?', 'multiple_choice', '["발명","혁신","기술","메커니즘"]'::jsonb, '발명', 'invention은 ''발명''이라는 뜻입니다.'),
  ('english_vocab', 13, 'beginner', '''technology''의 뜻으로 알맞은 것은?', 'multiple_choice', '["기술","혁신","발명","이론"]'::jsonb, '기술', 'technology는 ''기술''이라는 뜻입니다.'),
  ('english_vocab', 13, 'beginner', '''theory''의 뜻으로 알맞은 것은?', 'multiple_choice', '["이론","기기","메커니즘","분자"]'::jsonb, '이론', 'theory는 ''이론''이라는 뜻입니다.'),
  ('english_vocab', 13, 'beginner', '''laboratory''의 뜻으로 알맞은 것은?', 'multiple_choice', '["실험실","기기","발명","분자"]'::jsonb, '실험실', 'laboratory는 ''실험실''이라는 뜻입니다.'),
  ('english_vocab', 13, 'beginner', '''mechanism''의 뜻을 쓰시오.', 'short_answer', null, '메커니즘', 'mechanism은 ''메커니즘, 장치''라는 뜻입니다.'),
  ('english_vocab', 13, 'beginner', '''molecule''의 뜻을 쓰시오.', 'short_answer', null, '분자', 'molecule은 ''분자''라는 뜻입니다.'),
  ('english_vocab', 13, 'intermediate', '"Smartphones are a common electronic ___." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["device","mechanism","molecule","laboratory"]'::jsonb, 'device', 'device는 ''기기''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 13, 'intermediate', '"The company is known for its constant ___." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["innovation","invention","technology","theory"]'::jsonb, 'innovation', 'innovation은 ''혁신''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 13, 'intermediate', '"The light bulb was a groundbreaking ___." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["invention","innovation","device","mechanism"]'::jsonb, 'invention', 'invention은 ''발명''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 13, 'intermediate', '"Modern ___ has changed the way we communicate." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["technology","innovation","invention","mechanism"]'::jsonb, 'technology', 'technology는 ''기술''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 13, 'intermediate', '"Scientists proposed a new ___ to explain the phenomenon." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["theory","mechanism","molecule","invention"]'::jsonb, 'theory', 'theory는 ''이론''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 13, 'intermediate', '"The scientists conducted experiments in the ___." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["laboratory","mechanism","device","molecule"]'::jsonb, 'laboratory', 'laboratory는 ''실험실''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 13, 'intermediate', '"The safety ___ prevents the machine from overheating." 빈칸에 들어갈 단어를 쓰시오. (장치, 메커니즘)', 'short_answer', null, 'mechanism', 'mechanism은 ''메커니즘, 장치''라는 뜻입니다.'),
  ('english_vocab', 13, 'intermediate', '"Water is made of hydrogen and oxygen ___s." 빈칸에 들어갈 단어를 쓰시오. (분자)', 'short_answer', null, 'molecule', 'molecule은 ''분자''라는 뜻입니다.'),
  ('english_vocab', 13, 'advanced', '다음 중 의미가 나머지 셋과 가장 다른 것은?', 'multiple_choice', '["molecule","device","mechanism","invention"]'::jsonb, 'molecule', 'device, mechanism, invention은 모두 사람이 만든 도구나 장치를 뜻하지만 molecule은 자연적인 화학 단위인 ''분자''를 뜻하는 다른 의미입니다.'),
  ('english_vocab', 13, 'advanced', '''innovation''과 의미가 가장 가까운 단어는?', 'multiple_choice', '["breakthrough","theory","device","mechanism"]'::jsonb, 'breakthrough', 'innovation과 breakthrough는 모두 ''혁신, 획기적 발전''이라는 뜻입니다.'),
  ('english_vocab', 13, 'advanced', '"___ intelligence is transforming many industries." 문맥상 가장 적절한 것은?', 'multiple_choice', '["artificial","digital","mechanical","molecular"]'::jsonb, 'artificial', 'artificial intelligence는 ''인공지능''이라는 뜻의 표현입니다.'),
  ('english_vocab', 13, 'advanced', '''디지털의''라는 뜻을 가진 단어는?', 'multiple_choice', '["digital","artificial","technological","mechanical"]'::jsonb, 'digital', 'digital은 ''디지털의''라는 뜻입니다.'),
  ('english_vocab', 13, 'advanced', '"The clock''s internal ___ controls the hands'' movement." 문맥상 가장 적절한 것은?', 'multiple_choice', '["mechanism","device","molecule","theory"]'::jsonb, 'mechanism', 'mechanism은 ''메커니즘, 장치''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 13, 'advanced', '"a scientific ___" 빈칸에 가장 적절한 것은? (이론)', 'multiple_choice', '["theory","mechanism","molecule","innovation"]'::jsonb, 'theory', 'theory는 ''이론''이라는 뜻입니다.'),
  ('english_vocab', 13, 'advanced', '''혁신''이라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'innovation', 'innovation은 ''혁신''이라는 뜻입니다.'),
  ('english_vocab', 13, 'advanced', '''기기''라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'device', 'device는 ''기기''라는 뜻입니다.'),
  ('english_vocab', 14, 'beginner', '''symptom''의 뜻으로 알맞은 것은?', 'multiple_choice', '["증상","치료","질병","부상"]'::jsonb, '증상', 'symptom은 ''증상''이라는 뜻입니다.'),
  ('english_vocab', 14, 'beginner', '''treatment''의 뜻으로 알맞은 것은?', 'multiple_choice', '["치료","증상","약물","치료법"]'::jsonb, '치료', 'treatment는 ''치료''라는 뜻입니다.'),
  ('english_vocab', 14, 'beginner', '''disease''의 뜻으로 알맞은 것은?', 'multiple_choice', '["질병","증상","부상","피로"]'::jsonb, '질병', 'disease는 ''질병''이라는 뜻입니다.'),
  ('english_vocab', 14, 'beginner', '''injury''의 뜻으로 알맞은 것은?', 'multiple_choice', '["부상","질병","증상","피로"]'::jsonb, '부상', 'injury는 ''부상''이라는 뜻입니다.'),
  ('english_vocab', 14, 'beginner', '''medication''의 뜻으로 알맞은 것은?', 'multiple_choice', '["약물","치료","치료법","비타민"]'::jsonb, '약물', 'medication은 ''약물''이라는 뜻입니다.'),
  ('english_vocab', 14, 'beginner', '''therapy''의 뜻으로 알맞은 것은?', 'multiple_choice', '["치료법","치료","약물","증상"]'::jsonb, '치료법', 'therapy는 ''치료법''이라는 뜻입니다.'),
  ('english_vocab', 14, 'beginner', '''vitamin''의 뜻을 쓰시오.', 'short_answer', null, '비타민', 'vitamin은 ''비타민''이라는 뜻입니다.'),
  ('english_vocab', 14, 'beginner', '''fatigue''의 뜻을 쓰시오.', 'short_answer', null, '피로', 'fatigue는 ''피로''라는 뜻입니다.'),
  ('english_vocab', 14, 'intermediate', '"A high fever is a common ___ of the flu." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["symptom","treatment","disease","injury"]'::jsonb, 'symptom', 'symptom은 ''증상''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 14, 'intermediate', '"The patient responded well to the ___." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["treatment","medication","therapy","symptom"]'::jsonb, 'treatment', 'treatment는 ''치료''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 14, 'intermediate', '"Doctors are working to prevent the spread of the ___." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["disease","symptom","injury","fatigue"]'::jsonb, 'disease', 'disease는 ''질병''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 14, 'intermediate', '"He suffered a serious ___ during the game." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["injury","disease","symptom","fatigue"]'::jsonb, 'injury', 'injury는 ''부상''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 14, 'intermediate', '"Take this ___ twice a day after meals." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["medication","treatment","therapy","vitamin"]'::jsonb, 'medication', 'medication은 ''약물''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 14, 'intermediate', '"She attends physical ___ twice a week." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["therapy","treatment","medication","symptom"]'::jsonb, 'therapy', 'therapy는 ''치료법''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 14, 'intermediate', '"Oranges are rich in ___ C." 빈칸에 들어갈 단어를 쓰시오. (비타민)', 'short_answer', null, 'vitamin', 'vitamin은 ''비타민''이라는 뜻입니다.'),
  ('english_vocab', 14, 'intermediate', '"Long hours at work left her with severe ___." 빈칸에 들어갈 단어를 쓰시오. (피로)', 'short_answer', null, 'fatigue', 'fatigue는 ''피로''라는 뜻입니다.'),
  ('english_vocab', 14, 'advanced', '다음 중 의미가 나머지 셋과 가장 다른 것은?', 'multiple_choice', '["symptom","treatment","therapy","medication"]'::jsonb, 'symptom', 'treatment, therapy, medication은 모두 질병을 치료하는 방법을 뜻하지만 symptom은 질병의 ''증상, 징후''를 뜻하는 다른 의미입니다.'),
  ('english_vocab', 14, 'advanced', '''fatigue''와 의미가 가장 가까운 단어는?', 'multiple_choice', '["exhaustion","injury","nutrition","symptom"]'::jsonb, 'exhaustion', 'fatigue와 exhaustion은 모두 ''피로, 탈진''이라는 뜻입니다.'),
  ('english_vocab', 14, 'advanced', '"Good ___ is essential for a strong immune system." 문맥상 가장 적절한 것은?', 'multiple_choice', '["nutrition","medication","therapy","injury"]'::jsonb, 'nutrition', 'nutrition은 ''영양''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 14, 'advanced', '''면역의''라는 뜻을 가진 단어는?', 'multiple_choice', '["immune","medication","nutrition","therapy"]'::jsonb, 'immune', 'immune은 ''면역의''라는 뜻입니다.'),
  ('english_vocab', 14, 'advanced', '"The vaccine strengthens the body''s ___ system." 문맥상 가장 적절한 것은?', 'multiple_choice', '["immune","medication","nutrition","treatment"]'::jsonb, 'immune', 'immune은 ''면역의''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 14, 'advanced', '"balanced ___" 빈칸에 가장 적절한 것은? (영양)', 'multiple_choice', '["nutrition","medication","treatment","therapy"]'::jsonb, 'nutrition', 'nutrition은 ''영양''이라는 뜻입니다.'),
  ('english_vocab', 14, 'advanced', '''증상''이라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'symptom', 'symptom은 ''증상''이라는 뜻입니다.'),
  ('english_vocab', 14, 'advanced', '''질병''이라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'disease', 'disease는 ''질병''이라는 뜻입니다.'),
  ('english_vocab', 15, 'beginner', '''heritage''의 뜻으로 알맞은 것은?', 'multiple_choice', '["유산","걸작","조각","초상화"]'::jsonb, '유산', 'heritage는 ''유산''이라는 뜻입니다.'),
  ('english_vocab', 15, 'beginner', '''masterpiece''의 뜻으로 알맞은 것은?', 'multiple_choice', '["걸작","유산","조각","멜로디"]'::jsonb, '걸작', 'masterpiece는 ''걸작''이라는 뜻입니다.'),
  ('english_vocab', 15, 'beginner', '''sculpture''의 뜻으로 알맞은 것은?', 'multiple_choice', '["조각","초상화","걸작","유산"]'::jsonb, '조각', 'sculpture는 ''조각''이라는 뜻입니다.'),
  ('english_vocab', 15, 'beginner', '''literature''의 뜻으로 알맞은 것은?', 'multiple_choice', '["문학","유산","조각","창의성"]'::jsonb, '문학', 'literature는 ''문학''이라는 뜻입니다.'),
  ('english_vocab', 15, 'beginner', '''melody''의 뜻으로 알맞은 것은?', 'multiple_choice', '["멜로디","초상화","조각","걸작"]'::jsonb, '멜로디', 'melody는 ''멜로디''라는 뜻입니다.'),
  ('english_vocab', 15, 'beginner', '''portrait''의 뜻으로 알맞은 것은?', 'multiple_choice', '["초상화","조각","걸작","멜로디"]'::jsonb, '초상화', 'portrait는 ''초상화''라는 뜻입니다.'),
  ('english_vocab', 15, 'beginner', '''exhibit''의 뜻을 쓰시오.', 'short_answer', null, '전시하다', 'exhibit은 ''전시하다''라는 뜻입니다.'),
  ('english_vocab', 15, 'beginner', '''creativity''의 뜻을 쓰시오.', 'short_answer', null, '창의성', 'creativity는 ''창의성''이라는 뜻입니다.'),
  ('english_vocab', 15, 'intermediate', '"UNESCO protects sites of cultural ___." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["heritage","literature","sculpture","portrait"]'::jsonb, 'heritage', 'heritage는 ''유산''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 15, 'intermediate', '"This painting is considered a true ___." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["masterpiece","sculpture","portrait","melody"]'::jsonb, 'masterpiece', 'masterpiece는 ''걸작''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 15, 'intermediate', '"The museum displayed a bronze ___ in the courtyard." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["sculpture","portrait","masterpiece","heritage"]'::jsonb, 'sculpture', 'sculpture는 ''조각''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 15, 'intermediate', '"She studied classic English ___ at university." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["literature","heritage","sculpture","creativity"]'::jsonb, 'literature', 'literature는 ''문학''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 15, 'intermediate', '"The song''s ___ was simple but memorable." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["melody","portrait","sculpture","masterpiece"]'::jsonb, 'melody', 'melody는 ''멜로디''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 15, 'intermediate', '"The artist painted a ___ of the king." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["portrait","sculpture","masterpiece","melody"]'::jsonb, 'portrait', 'portrait는 ''초상화''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 15, 'intermediate', '"The gallery will ___ new paintings next month." 빈칸에 들어갈 단어를 쓰시오. (전시하다)', 'short_answer', null, 'exhibit', 'exhibit은 ''전시하다''라는 뜻입니다.'),
  ('english_vocab', 15, 'intermediate', '"The children showed great ___ in their drawings." 빈칸에 들어갈 단어를 쓰시오. (창의성)', 'short_answer', null, 'creativity', 'creativity는 ''창의성''이라는 뜻입니다.'),
  ('english_vocab', 15, 'advanced', '다음 중 의미가 나머지 셋과 가장 다른 것은?', 'multiple_choice', '["creativity","masterpiece","sculpture","portrait"]'::jsonb, 'creativity', 'masterpiece, sculpture, portrait는 모두 구체적인 예술 작품을 뜻하지만 creativity는 창작하는 ''능력''을 뜻하는 다른 의미입니다.'),
  ('english_vocab', 15, 'advanced', '''미적인''이라는 뜻을 가진 단어는?', 'multiple_choice', '["aesthetic","artistic","historic","cultural"]'::jsonb, 'aesthetic', 'aesthetic은 ''미적인''이라는 뜻입니다.'),
  ('english_vocab', 15, 'advanced', '''예술적인''이라는 뜻을 가진 단어는?', 'multiple_choice', '["artistic","aesthetic","historic","ethnic"]'::jsonb, 'artistic', 'artistic은 ''예술적인''이라는 뜻입니다.'),
  ('english_vocab', 15, 'advanced', '"This exhibition showcases the nation''s cultural ___." 문맥상 가장 적절한 것은?', 'multiple_choice', '["heritage","masterpiece","sculpture","portrait"]'::jsonb, 'heritage', 'heritage는 ''유산''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 15, 'advanced', '"a literary ___" 빈칸에 가장 적절한 것은? (걸작)', 'multiple_choice', '["masterpiece","sculpture","portrait","heritage"]'::jsonb, 'masterpiece', 'masterpiece는 ''걸작''이라는 뜻입니다.'),
  ('english_vocab', 15, 'advanced', '"The design has great ___ appeal, pleasing to the eye." 문맥상 가장 적절한 것은?', 'multiple_choice', '["aesthetic","artistic","historic","cultural"]'::jsonb, 'aesthetic', 'aesthetic appeal은 ''미적 매력''이라는 뜻의 표현입니다.'),
  ('english_vocab', 15, 'advanced', '''유산''이라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'heritage', 'heritage는 ''유산''이라는 뜻입니다.'),
  ('english_vocab', 15, 'advanced', '''조각''이라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'sculpture', 'sculpture는 ''조각''이라는 뜻입니다.');
