-- english_vocab question_bank seed — generated from c:/git_repository/5minuate_study/supabase/seed/english_vocab_day16-20.json
-- Supabase SQL 에디터에서 실행하세요 (question_bank 테이블이 먼저 생성되어 있어야 함)

insert into question_bank (curriculum_id, day_num, difficulty, question, type, options, answer, explanation) values
  ('english_vocab', 16, 'beginner', '''authority''의 뜻으로 알맞은 것은?', 'multiple_choice', '["권위, 당국","캠페인","민주주의","정책"]'::jsonb, '권위, 당국', 'authority는 ''권위, 당국''이라는 뜻입니다.'),
  ('english_vocab', 16, 'beginner', '''campaign''의 뜻으로 알맞은 것은?', 'multiple_choice', '["캠페인","의회","정책","규정"]'::jsonb, '캠페인', 'campaign은 ''캠페인''이라는 뜻입니다.'),
  ('english_vocab', 16, 'beginner', '''democracy''의 뜻으로 알맞은 것은?', 'multiple_choice', '["민주주의","의회","캠페인","권위"]'::jsonb, '민주주의', 'democracy는 ''민주주의''라는 뜻입니다.'),
  ('english_vocab', 16, 'beginner', '''policy''의 뜻으로 알맞은 것은?', 'multiple_choice', '["정책","규정","캠페인","입법"]'::jsonb, '정책', 'policy는 ''정책''이라는 뜻입니다.'),
  ('english_vocab', 16, 'beginner', '''regulation''의 뜻으로 알맞은 것은?', 'multiple_choice', '["규정","정책","선거","정의"]'::jsonb, '규정', 'regulation은 ''규정''이라는 뜻입니다.'),
  ('english_vocab', 16, 'beginner', '''election''의 뜻으로 알맞은 것은?', 'multiple_choice', '["선거","캠페인","의회","민주주의"]'::jsonb, '선거', 'election은 ''선거''라는 뜻입니다.'),
  ('english_vocab', 16, 'beginner', '''congress''의 뜻을 쓰시오.', 'short_answer', null, '의회', 'congress는 ''의회''라는 뜻입니다.'),
  ('english_vocab', 16, 'beginner', '''legislation''의 뜻을 쓰시오.', 'short_answer', null, '법률', 'legislation은 ''법률, 입법''이라는 뜻입니다.'),
  ('english_vocab', 16, 'intermediate', '"The local ___ issued a new permit." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["authority","campaign","election","congress"]'::jsonb, 'authority', 'authority는 ''당국''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 16, 'intermediate', '"He ran an aggressive election ___." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["campaign","congress","policy","regulation"]'::jsonb, 'campaign', 'campaign은 ''캠페인''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 16, 'intermediate', '"The country transitioned to a ___ after decades of dictatorship." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["democracy","congress","campaign","authority"]'::jsonb, 'democracy', 'democracy는 ''민주주의''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 16, 'intermediate', '"The factory must comply with strict safety ___s." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["regulation","policy","legislation","campaign"]'::jsonb, 'regulation', 'regulation은 ''규정''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 16, 'intermediate', '"The new economic ___ aims to reduce inflation." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["policy","regulation","campaign","legislation"]'::jsonb, 'policy', 'policy는 ''정책''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 16, 'intermediate', '"Millions of citizens voted in the presidential ___." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["election","campaign","congress","democracy"]'::jsonb, 'election', 'election은 ''선거''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 16, 'intermediate', '"The bill passed ___ after a long debate." 빈칸에 들어갈 단어를 쓰시오. (의회)', 'short_answer', null, 'congress', 'congress는 ''의회''라는 뜻입니다.'),
  ('english_vocab', 16, 'intermediate', '"The parliament passed new ___ to protect workers." 빈칸에 들어갈 단어를 쓰시오. (법률, 입법)', 'short_answer', null, 'legislation', 'legislation은 ''법률, 입법''이라는 뜻입니다.'),
  ('english_vocab', 16, 'advanced', '다음 중 의미가 나머지 셋과 가장 다른 것은?', 'multiple_choice', '["violation","policy","regulation","legislation"]'::jsonb, 'violation', 'policy, regulation, legislation은 모두 규칙을 만드는 것과 관련되지만 violation은 규칙을 어기는 ''위반''이라는 다른 의미입니다.'),
  ('english_vocab', 16, 'advanced', '''authority''와 의미가 가장 가까운 단어는?', 'multiple_choice', '["power","justice","campaign","election"]'::jsonb, 'power', 'authority와 power는 모두 ''권력, 권위''라는 뜻입니다.'),
  ('english_vocab', 16, 'advanced', '"The company was fined for a serious ___ of safety regulations." 문맥상 가장 적절한 것은?', 'multiple_choice', '["violation","authority","campaign","congress"]'::jsonb, 'violation', 'violation은 ''위반''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 16, 'advanced', '''정의''라는 뜻을 가진 단어는?', 'multiple_choice', '["justice","democracy","authority","legislation"]'::jsonb, 'justice', 'justice는 ''정의''라는 뜻입니다.'),
  ('english_vocab', 16, 'advanced', '"The senator launched a national ___ for education reform." 문맥상 가장 적절한 것은?', 'multiple_choice', '["campaign","violation","congress","regulation"]'::jsonb, 'campaign', 'campaign은 ''캠페인, 운동''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 16, 'advanced', '"Freedom of speech is a core principle of ___." 빈칸에 가장 적절한 것은?', 'multiple_choice', '["democracy","authority","campaign","justice"]'::jsonb, 'democracy', 'democracy는 ''민주주의''라는 뜻입니다.'),
  ('english_vocab', 16, 'advanced', '''권위, 당국''이라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'authority', 'authority는 ''권위, 당국''이라는 뜻입니다.'),
  ('english_vocab', 16, 'advanced', '''위반''이라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'violation', 'violation은 ''위반''이라는 뜻입니다.'),
  ('english_vocab', 17, 'beginner', '''ancestor''의 뜻으로 알맞은 것은?', 'multiple_choice', '["조상","문명","왕조","유산"]'::jsonb, '조상', 'ancestor는 ''조상''이라는 뜻입니다.'),
  ('english_vocab', 17, 'beginner', '''civilization''의 뜻으로 알맞은 것은?', 'multiple_choice', '["문명","조상","시대","기념물"]'::jsonb, '문명', 'civilization은 ''문명''이라는 뜻입니다.'),
  ('english_vocab', 17, 'beginner', '''dynasty''의 뜻으로 알맞은 것은?', 'multiple_choice', '["왕조","문명","유산","신화"]'::jsonb, '왕조', 'dynasty는 ''왕조''라는 뜻입니다.'),
  ('english_vocab', 17, 'beginner', '''era''의 뜻으로 알맞은 것은?', 'multiple_choice', '["시대","왕조","유산","의식"]'::jsonb, '시대', 'era는 ''시대''라는 뜻입니다.'),
  ('english_vocab', 17, 'beginner', '''legacy''의 뜻으로 알맞은 것은?', 'multiple_choice', '["유산","신화","의식","기념물"]'::jsonb, '유산', 'legacy는 ''유산''이라는 뜻입니다.'),
  ('english_vocab', 17, 'beginner', '''monument''의 뜻으로 알맞은 것은?', 'multiple_choice', '["기념물","신화","의식","유산"]'::jsonb, '기념물', 'monument는 ''기념물''이라는 뜻입니다.'),
  ('english_vocab', 17, 'beginner', '''myth''의 뜻을 쓰시오.', 'short_answer', null, '신화', 'myth는 ''신화''라는 뜻입니다.'),
  ('english_vocab', 17, 'beginner', '''ritual''의 뜻을 쓰시오.', 'short_answer', null, '의식', 'ritual은 ''의식''이라는 뜻입니다.'),
  ('english_vocab', 17, 'intermediate', '"This tradition has been passed down from our ___s." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["ancestor","dynasty","legacy","era"]'::jsonb, 'ancestor', 'ancestor는 ''조상''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 17, 'intermediate', '"Ancient Egyptian ___ built the pyramids." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["civilization","dynasty","era","monument"]'::jsonb, 'civilization', 'civilization은 ''문명''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 17, 'intermediate', '"The Joseon ___ ruled Korea for over 500 years." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["dynasty","era","civilization","legacy"]'::jsonb, 'dynasty', 'dynasty는 ''왕조''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 17, 'intermediate', '"We are entering a new ___ of technology." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["era","dynasty","legacy","ritual"]'::jsonb, 'era', 'era는 ''시대''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 17, 'intermediate', '"He left behind a lasting ___ of kindness." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["legacy","myth","ritual","monument"]'::jsonb, 'legacy', 'legacy는 ''유산''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 17, 'intermediate', '"The statue is a famous historic ___." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["monument","myth","ritual","legacy"]'::jsonb, 'monument', 'monument는 ''기념물''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 17, 'intermediate', '"According to Greek ___, the gods lived on Mount Olympus." 빈칸에 들어갈 단어를 쓰시오. (신화)', 'short_answer', null, 'myth', 'myth는 ''신화''라는 뜻입니다.'),
  ('english_vocab', 17, 'intermediate', '"The wedding ___ lasted for three days." 빈칸에 들어갈 단어를 쓰시오. (의식)', 'short_answer', null, 'ritual', 'ritual은 ''의식''이라는 뜻입니다.'),
  ('english_vocab', 17, 'advanced', '다음 중 의미가 나머지 셋과 가장 다른 것은?', 'multiple_choice', '["chronicle","myth","ritual","monument"]'::jsonb, 'chronicle', 'myth, ritual, monument는 모두 문화적 산물이지만 chronicle은 ''기록하다''라는 행위를 뜻하는 다른 의미입니다.'),
  ('english_vocab', 17, 'advanced', '''legacy''와 의미가 가장 가까운 단어는?', 'multiple_choice', '["heritage","myth","ritual","era"]'::jsonb, 'heritage', 'legacy와 heritage는 모두 ''유산''이라는 뜻입니다.'),
  ('english_vocab', 17, 'advanced', '"This museum ___s the history of the region." 문맥상 가장 적절한 것은?', 'multiple_choice', '["chronicles","monuments","myths","rituals"]'::jsonb, 'chronicles', 'chronicle은 동사로 ''기록하다''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 17, 'advanced', '''역사적인''이라는 뜻을 가진 단어는?', 'multiple_choice', '["historic","ancient","mythical","ritual"]'::jsonb, 'historic', 'historic은 ''역사적인''이라는 뜻입니다.'),
  ('english_vocab', 17, 'advanced', '"The signing of the treaty was a ___ moment." 문맥상 가장 적절한 것은?', 'multiple_choice', '["historic","mythical","ritual","ancestral"]'::jsonb, 'historic', 'historic은 ''역사적인''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 17, 'advanced', '"Scholars study ancient ___s to understand early human societies." 빈칸에 가장 적절한 것은?', 'multiple_choice', '["civilizations","dynasties","legacies","monuments"]'::jsonb, 'civilizations', 'civilization은 ''문명''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 17, 'advanced', '''유산''이라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'legacy', 'legacy는 ''유산''이라는 뜻입니다.'),
  ('english_vocab', 17, 'advanced', '''왕조''라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'dynasty', 'dynasty는 ''왕조''라는 뜻입니다.'),
  ('english_vocab', 18, 'beginner', '''arrogant''의 뜻으로 알맞은 것은?', 'multiple_choice', '["거만한","신중한","관대한","겸손한"]'::jsonb, '거만한', 'arrogant는 ''거만한''이라는 뜻입니다.'),
  ('english_vocab', 18, 'beginner', '''cautious''의 뜻으로 알맞은 것은?', 'multiple_choice', '["신중한","거만한","낙관적인","고집 센"]'::jsonb, '신중한', 'cautious는 ''신중한''이라는 뜻입니다.'),
  ('english_vocab', 18, 'beginner', '''generous''의 뜻으로 알맞은 것은?', 'multiple_choice', '["관대한","거만한","겸손한","비관적인"]'::jsonb, '관대한', 'generous는 ''관대한''이라는 뜻입니다.'),
  ('english_vocab', 18, 'beginner', '''humble''의 뜻으로 알맞은 것은?', 'multiple_choice', '["겸손한","거만한","신중한","고집 센"]'::jsonb, '겸손한', 'humble은 ''겸손한''이라는 뜻입니다.'),
  ('english_vocab', 18, 'beginner', '''optimistic''의 뜻으로 알맞은 것은?', 'multiple_choice', '["낙관적인","비관적인","신중한","고집 센"]'::jsonb, '낙관적인', 'optimistic은 ''낙관적인''이라는 뜻입니다.'),
  ('english_vocab', 18, 'beginner', '''stubborn''의 뜻으로 알맞은 것은?', 'multiple_choice', '["고집 센","겸손한","낙관적인","관대한"]'::jsonb, '고집 센', 'stubborn은 ''고집 센''이라는 뜻입니다.'),
  ('english_vocab', 18, 'beginner', '''pessimistic''의 뜻을 쓰시오.', 'short_answer', null, '비관적인', 'pessimistic은 ''비관적인''이라는 뜻입니다.'),
  ('english_vocab', 18, 'beginner', '''sincere''의 뜻을 쓰시오.', 'short_answer', null, '진실한', 'sincere는 ''진실한''이라는 뜻입니다.'),
  ('english_vocab', 18, 'intermediate', '"He is too ___ to admit his mistakes." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["arrogant","humble","cautious","generous"]'::jsonb, 'arrogant', 'arrogant는 ''거만한''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 18, 'intermediate', '"She is a ___ driver who always checks her mirrors." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["cautious","arrogant","stubborn","sensitive"]'::jsonb, 'cautious', 'cautious는 ''신중한''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 18, 'intermediate', '"He made a ___ donation to the charity." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["generous","humble","cautious","pessimistic"]'::jsonb, 'generous', 'generous는 ''관대한''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 18, 'intermediate', '"Despite his success, he remained ___." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["humble","arrogant","stubborn","sensitive"]'::jsonb, 'humble', 'humble은 ''겸손한''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 18, 'intermediate', '"She has an ___ view of the future." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["optimistic","pessimistic","cautious","stubborn"]'::jsonb, 'optimistic', 'optimistic은 ''낙관적인''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 18, 'intermediate', '"My grandfather is ___ and never changes his mind." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["stubborn","humble","optimistic","generous"]'::jsonb, 'stubborn', 'stubborn은 ''고집 센''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 18, 'intermediate', '"He always expects the worst; he''s very ___." 빈칸에 들어갈 단어를 쓰시오. (비관적인)', 'short_answer', null, 'pessimistic', 'pessimistic은 ''비관적인''이라는 뜻입니다.'),
  ('english_vocab', 18, 'intermediate', '"She gave a ___ apology for her mistake." 빈칸에 들어갈 단어를 쓰시오. (진실한)', 'short_answer', null, 'sincere', 'sincere는 ''진실한''이라는 뜻입니다.'),
  ('english_vocab', 18, 'advanced', '다음 중 의미가 나머지 셋과 가장 다른 것은?', 'multiple_choice', '["arrogant","humble","modest","sincere"]'::jsonb, 'arrogant', 'humble, modest, sincere는 모두 겸손하고 진실된 긍정적 성격이지만 arrogant는 ''거만한''이라는 반대 의미입니다.'),
  ('english_vocab', 18, 'advanced', '''humble''과 의미가 가장 가까운 단어는?', 'multiple_choice', '["modest","arrogant","stubborn","optimistic"]'::jsonb, 'modest', 'humble과 modest는 모두 ''겸손한''이라는 뜻입니다.'),
  ('english_vocab', 18, 'advanced', '"This is a very ___ topic, so please be careful with your words." 문맥상 가장 적절한 것은?', 'multiple_choice', '["sensitive","generous","stubborn","cautious"]'::jsonb, 'sensitive', 'sensitive는 ''민감한''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 18, 'advanced', '''고집 센''이라는 뜻을 가진 단어는?', 'multiple_choice', '["stubborn","cautious","sincere","modest"]'::jsonb, 'stubborn', 'stubborn은 ''고집 센''이라는 뜻입니다.'),
  ('english_vocab', 18, 'advanced', '"Despite the setback, she remained ___ about the project''s success." 문맥상 가장 적절한 것은?', 'multiple_choice', '["optimistic","pessimistic","arrogant","stubborn"]'::jsonb, 'optimistic', 'optimistic은 ''낙관적인''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 18, 'advanced', '"He lives a ___ lifestyle despite his wealth." 빈칸에 가장 적절한 것은?', 'multiple_choice', '["modest","arrogant","sensitive","stubborn"]'::jsonb, 'modest', 'modest는 ''검소한, 적당한''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 18, 'advanced', '''민감한''이라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'sensitive', 'sensitive는 ''민감한''이라는 뜻입니다.'),
  ('english_vocab', 18, 'advanced', '''적당한, 겸손한''이라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'modest', 'modest는 ''겸손한, 적당한''이라는 뜻입니다.'),
  ('english_vocab', 19, 'beginner', '''convey''의 뜻으로 알맞은 것은?', 'multiple_choice', '["전달하다","설득하다","협상하다","강조하다"]'::jsonb, '전달하다', 'convey는 ''전달하다''라는 뜻입니다.'),
  ('english_vocab', 19, 'beginner', '''persuade''의 뜻으로 알맞은 것은?', 'multiple_choice', '["설득하다","전달하다","해석하다","표현하다"]'::jsonb, '설득하다', 'persuade는 ''설득하다''라는 뜻입니다.'),
  ('english_vocab', 19, 'beginner', '''negotiate''의 뜻으로 알맞은 것은?', 'multiple_choice', '["협상하다","설득하다","강조하다","암시하다"]'::jsonb, '협상하다', 'negotiate는 ''협상하다''라는 뜻입니다.'),
  ('english_vocab', 19, 'beginner', '''emphasize''의 뜻으로 알맞은 것은?', 'multiple_choice', '["강조하다","협상하다","해석하다","명확히 하다"]'::jsonb, '강조하다', 'emphasize는 ''강조하다''라는 뜻입니다.'),
  ('english_vocab', 19, 'beginner', '''interpret''의 뜻으로 알맞은 것은?', 'multiple_choice', '["해석하다","전달하다","표현하다","설득하다"]'::jsonb, '해석하다', 'interpret은 ''해석하다''라는 뜻입니다.'),
  ('english_vocab', 19, 'beginner', '''express''의 뜻으로 알맞은 것은?', 'multiple_choice', '["표현하다","암시하다","명확히 하다","상세히 설명하다"]'::jsonb, '표현하다', 'express는 ''표현하다''라는 뜻입니다.'),
  ('english_vocab', 19, 'beginner', '''clarify''의 뜻을 쓰시오.', 'short_answer', null, '명확히 하다', 'clarify는 ''명확히 하다''라는 뜻입니다.'),
  ('english_vocab', 19, 'beginner', '''elaborate''의 뜻을 쓰시오.', 'short_answer', null, '상세히 설명하다', 'elaborate는 ''상세히 설명하다''라는 뜻입니다.'),
  ('english_vocab', 19, 'intermediate', '"The letter failed to ___ the urgency of the situation." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["convey","persuade","negotiate","imply"]'::jsonb, 'convey', 'convey는 ''전달하다''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 19, 'intermediate', '"She tried to ___ him to join the team." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["persuade","convey","negotiate","emphasize"]'::jsonb, 'persuade', 'persuade는 ''설득하다''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 19, 'intermediate', '"The two companies will ___ a new deal next week." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["negotiate","persuade","convey","interpret"]'::jsonb, 'negotiate', 'negotiate는 ''협상하다''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 19, 'intermediate', '"The teacher ___d the importance of practice." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["emphasize","imply","interpret","clarify"]'::jsonb, 'emphasize', 'emphasize는 ''강조하다''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 19, 'intermediate', '"It''s hard to ___ what she really meant." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["interpret","convey","emphasize","express"]'::jsonb, 'interpret', 'interpret은 ''해석하다''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 19, 'intermediate', '"He couldn''t ___ his feelings in words." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["express","imply","clarify","elaborate"]'::jsonb, 'express', 'express는 ''표현하다''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 19, 'intermediate', '"Could you ___ your point? I don''t quite understand." 빈칸에 들어갈 단어를 쓰시오. (명확히 하다)', 'short_answer', null, 'clarify', 'clarify는 ''명확히 하다''라는 뜻입니다.'),
  ('english_vocab', 19, 'intermediate', '"Could you ___ on that idea a bit more?" 빈칸에 들어갈 단어를 쓰시오. (상세히 설명하다)', 'short_answer', null, 'elaborate', 'elaborate는 ''상세히 설명하다''라는 뜻입니다.'),
  ('english_vocab', 19, 'advanced', '다음 중 의미가 나머지 셋과 가장 다른 것은?', 'multiple_choice', '["imply","express","articulate","convey"]'::jsonb, 'imply', 'express, articulate, convey는 모두 명확하게 전달한다는 뜻이지만 imply는 간접적으로 나타낸다는 ''암시하다''의 다른 의미입니다.'),
  ('english_vocab', 19, 'advanced', '''articulate''와 의미가 가장 가까운 표현은?', 'multiple_choice', '["express clearly","negotiate","imply","interpret"]'::jsonb, 'express clearly', 'articulate는 ''명확히 표현하다''라는 뜻입니다.'),
  ('english_vocab', 19, 'advanced', '"Are you ___ that I made a mistake?" 문맥상 가장 적절한 것은?', 'multiple_choice', '["implying","clarifying","articulating","negotiating"]'::jsonb, 'implying', 'imply는 ''암시하다''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 19, 'advanced', '''명확히 표현하다''라는 뜻을 가진 단어는?', 'multiple_choice', '["articulate","imply","negotiate","interpret"]'::jsonb, 'articulate', 'articulate는 ''명확히 표현하다''라는 뜻입니다.'),
  ('english_vocab', 19, 'advanced', '"The two sides failed to ___ a peaceful resolution." 문맥상 가장 적절한 것은?', 'multiple_choice', '["negotiate","imply","articulate","convey"]'::jsonb, 'negotiate', 'negotiate는 ''협상하다''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 19, 'advanced', '"The data can be ___ed in several different ways." 빈칸에 가장 적절한 것은?', 'multiple_choice', '["interpreted","conveyed","articulated","emphasized"]'::jsonb, 'interpreted', 'interpret은 ''해석하다''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 19, 'advanced', '''암시하다''라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'imply', 'imply는 ''암시하다''라는 뜻입니다.'),
  ('english_vocab', 19, 'advanced', '''명확히 표현하다''라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'articulate', 'articulate는 ''명확히 표현하다''라는 뜻입니다.'),
  ('english_vocab', 20, 'beginner', '''pollution''의 뜻으로 알맞은 것은?', 'multiple_choice', '["오염","자원","배출","생태계"]'::jsonb, '오염', 'pollution은 ''오염''이라는 뜻입니다.'),
  ('english_vocab', 20, 'beginner', '''resource''의 뜻으로 알맞은 것은?', 'multiple_choice', '["자원","오염","생태계","배출"]'::jsonb, '자원', 'resource는 ''자원''이라는 뜻입니다.'),
  ('english_vocab', 20, 'beginner', '''sustainable''의 뜻으로 알맞은 것은?', 'multiple_choice', '["지속 가능한","재생 가능한","오염된","화석의"]'::jsonb, '지속 가능한', 'sustainable은 ''지속 가능한''이라는 뜻입니다.'),
  ('english_vocab', 20, 'beginner', '''emission''의 뜻으로 알맞은 것은?', 'multiple_choice', '["배출","오염","자원","생태계"]'::jsonb, '배출', 'emission은 ''배출''이라는 뜻입니다.'),
  ('english_vocab', 20, 'beginner', '''ecosystem''의 뜻으로 알맞은 것은?', 'multiple_choice', '["생태계","오염","자원","배출"]'::jsonb, '생태계', 'ecosystem은 ''생태계''라는 뜻입니다.'),
  ('english_vocab', 20, 'beginner', '''recycle''의 뜻으로 알맞은 것은?', 'multiple_choice', '["재활용하다","보존하다","소모시키다","오염시키다"]'::jsonb, '재활용하다', 'recycle은 ''재활용하다''라는 뜻입니다.'),
  ('english_vocab', 20, 'beginner', '''renewable''의 뜻을 쓰시오.', 'short_answer', null, '재생 가능한', 'renewable은 ''재생 가능한''이라는 뜻입니다.'),
  ('english_vocab', 20, 'beginner', '''conserve''의 뜻을 쓰시오.', 'short_answer', null, '보존하다', 'conserve는 ''보존하다, 아끼다''라는 뜻입니다.'),
  ('english_vocab', 20, 'intermediate', '"Air ___ is a serious problem in big cities." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["pollution","emission","resource","ecosystem"]'::jsonb, 'pollution', 'pollution은 ''오염''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 20, 'intermediate', '"Water is a precious natural ___." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["resource","pollution","emission","ecosystem"]'::jsonb, 'resource', 'resource는 ''자원''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 20, 'intermediate', '"The company adopted a ___ business model to protect the environment." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["sustainable","renewable","profitable","traditional"]'::jsonb, 'sustainable', 'sustainable은 ''지속 가능한''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 20, 'intermediate', '"Carbon ___ from factories must be reduced." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["emission","pollution","resource","ecosystem"]'::jsonb, 'emission', 'emission은 ''배출''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 20, 'intermediate', '"The coral reef is a fragile ___." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["ecosystem","resource","emission","pollution"]'::jsonb, 'ecosystem', 'ecosystem은 ''생태계''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 20, 'intermediate', '"We should ___ plastic bottles instead of throwing them away." 빈칸에 가장 알맞은 것은?', 'multiple_choice', '["recycle","conserve","produce","consume"]'::jsonb, 'recycle', 'recycle은 ''재활용하다''라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 20, 'intermediate', '"Solar and wind power are examples of ___ energy." 빈칸에 들어갈 단어를 쓰시오. (재생 가능한)', 'short_answer', null, 'renewable', 'renewable은 ''재생 가능한''이라는 뜻입니다.'),
  ('english_vocab', 20, 'intermediate', '"We should ___ water during the drought." 빈칸에 들어갈 단어를 쓰시오. (보존하다, 아끼다)', 'short_answer', null, 'conserve', 'conserve는 ''보존하다, 아끼다''라는 뜻입니다.'),
  ('english_vocab', 20, 'advanced', '다음 중 의미가 나머지 셋과 가장 다른 것은?', 'multiple_choice', '["fossil","pollution","emission","exhaust"]'::jsonb, 'fossil', 'pollution, emission, exhaust는 모두 오염·배출과 관련되지만 fossil은 ''화석''을 뜻하는 다른 의미입니다.'),
  ('english_vocab', 20, 'advanced', '''sustainable''과 의미가 가장 가까운 단어는?', 'multiple_choice', '["renewable","harmful","temporary","artificial"]'::jsonb, 'renewable', 'sustainable과 renewable은 모두 환경을 유지·재생할 수 있다는 뜻으로 통합니다.'),
  ('english_vocab', 20, 'advanced', '"___ fuels like coal and oil are a major source of pollution." 문맥상 가장 적절한 것은?', 'multiple_choice', '["Fossil","Renewable","Sustainable","Recycled"]'::jsonb, 'Fossil', 'fossil fuel은 ''화석 연료''라는 뜻의 표현입니다.'),
  ('english_vocab', 20, 'advanced', '''지속 가능한''이라는 뜻을 가진 단어는?', 'multiple_choice', '["sustainable","renewable","fossil","disposable"]'::jsonb, 'sustainable', 'sustainable은 ''지속 가능한''이라는 뜻입니다.'),
  ('english_vocab', 20, 'advanced', '"Car ___ contains harmful gases." 문맥상 가장 적절한 것은?', 'multiple_choice', '["exhaust","resource","ecosystem","emission"]'::jsonb, 'exhaust', 'car exhaust는 ''자동차 배기가스''라는 뜻의 고정 표현입니다.'),
  ('english_vocab', 20, 'advanced', '"The government aims to reduce carbon ___s by 2030." 빈칸에 가장 적절한 것은?', 'multiple_choice', '["emissions","exhaust","pollution","fossils"]'::jsonb, 'emissions', 'emission은 ''배출''이라는 뜻으로 이 문맥에 맞습니다.'),
  ('english_vocab', 20, 'advanced', '''화석''이라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'fossil', 'fossil은 ''화석''이라는 뜻입니다.'),
  ('english_vocab', 20, 'advanced', '''배기가스''라는 뜻의 단어를 쓰시오.', 'short_answer', null, 'exhaust', 'exhaust는 ''배기가스''라는 뜻입니다(동사로는 ''소모시키다'').');
